### PR TITLE
Initial commit for the kotlin FieldFilter classes.

### PR DESCRIPTION
**Pull request by wangyaopw**
Need to implement field_filter.utiles first.

This is to implement the [field_filters](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/main/src/main/cc/wfa/virtual_people/common/field_filter/field_filter.h) in Kotlin.

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37)

### CODE REVIEW

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @tcsnfkx, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAQt8ib5gSjDovcwPqb:-NAQt8ib5gSjDovcwPqc:bihnbrj) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/017ec146a6924d6d9939f40346005c7ba570d53a/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L36)):*
> ```Kotlin
> // Users should never call the factory functions or the constructors of the
> // derived classes.
> fun newFieldFilter(descriptor: Descriptor, config: FieldFilterProto): FieldFilter {
> ```

@sanjayvas 

Need your input on how to define the interface.

It is a little weird, since it is expected to only create instances with type equals to the interface.  No inherited class object will be created directly.

https://github.com/world-federation-of-advertisers/virtual-people-common/blob/main/src/main/cc/wfa/virtual_people/common/field_filter/field_filter.h#L38



_Code quote:_
```Kotlin
newFieldFilter
```

**Comment by wangyaopw** [comment]
CC  @JuliethHernandez

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37)* status: 7 of 11 files reviewed, 4 unresolved discussions (waiting on @tcsnfkx, @wangyaopw, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAelTHd6EC1cyp4ht7J:-NAelTHd6EC1cyp4ht7K:bpe2y4j) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/017ec146a6924d6d9939f40346005c7ba570d53a/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L23)):*
> ```Kotlin
> 
> // This is the Kotlin implementation of FieldFilterProto.
> // @descriptor defines the target protobuf message type this FieldFilter checks.
> ```

Use KDoc syntax for types, functions, and properties. Follow [style guide](https://developer.android.com/kotlin/style-guide#documentation)



_Code quote:_
```Kotlin
// This is the Kotlin implementation of FieldFilterProto.
// @descriptor defines the target protobuf message type this FieldFilter checks.
// @config defines the checks that will be performed when calling IsMatch.
//
// This is the interface for all FieldFilter classes. Never add any behavior
// here.
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAem7Hy4oaS6RIxWyAN:-NAem7Hz1A_DO9TqW4Nq:b-x859qq) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/017ec146a6924d6d9939f40346005c7ba570d53a/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L30)):*
> ```Kotlin
> interface FieldFilter {
>   // Returns true if the @message satisfies the condition described by the FieldFilter
>   fun isMatch(message: Message)
> ```

nit: `matches` would be more idiomatic Kotlin



_Code quote:_
```Kotlin
isMatch
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAQt8ib5gSjDovcwPqb:-NAejMNZ2JcJgilwMnGy:b-hzhao4) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/017ec146a6924d6d9939f40346005c7ba570d53a/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L36)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

@sanjayvas 

Need your input on how to define the interface.

It is a little weird, since it is expected to only create instances with type equals to the interface.  No inherited class object will be created directly.

https://github.com/world-federation-of-advertisers/virtual-people-common/blob/main/src/main/cc/wfa/virtual_people/common/field_filter/field_filter.h#L38
</blockquote></details>

It's fine to have an interface that has no public implementation. That said, I am slightly confused as the documentation says this is a Kotlin version of something called `FieldFilterProto`, which to me sounds like a protobuf message type. Indeed, the factory function takes in a `FieldFilterProto` object so I'm not sure how this can be the Kotlin version of said type.

Looking at the C++ code, it does look like there are indeed concrete implementations of filters e.g. `EqualsFilter`. I assume these would just be private classes with different implementation of `isMatch`. Using a sealed interface would also prevent implementations from being defined outside of this library target.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAemYn04MiqCDmGg4Ho:-NAemYn04MiqCDmGg4Hp:b-rp1d66) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/017ec146a6924d6d9939f40346005c7ba570d53a/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L36)):*
> ```Kotlin
> // Users should never call the factory functions or the constructors of the
> // derived classes.
> fun newFieldFilter(descriptor: Descriptor, config: FieldFilterProto): FieldFilter {
> ```

Idiomatic Kotlin would be to either put the factory functions inside of a companion object or to use pseudo-constructors. Note that pseudo-constructors (or any top-level functions defined in Kotlin) are slightly uglier to call from Java, as they get placed inside of a generated "Kt" class for that. Therefore, I'd recommend not having any public top-level functions that are intended to be callable from Java or other JVM languages.

Maybe just `create` functions in the companion object of the interface annotated with `@JvmStatic` so they can be called from Java.



_Code quote:_
```Kotlin
newFieldFilter
```

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37)* status: 7 of 11 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @tcsnfkx, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAelTHd6EC1cyp4ht7J:-NAf8EMB9l8OyQJ71ijQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/017ec146a6924d6d9939f40346005c7ba570d53a/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use KDoc syntax for types, functions, and properties. Follow [style guide](https://developer.android.com/kotlin/style-guide#documentation)
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAem7Hy4oaS6RIxWyAN:-NAf8Qu_AN9AQg7GcfHk:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/017ec146a6924d6d9939f40346005c7ba570d53a/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: `matches` would be more idiomatic Kotlin
</blockquote></details>

done
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAemYn04MiqCDmGg4Ho:-NAf9Jeh6d9xsUW8wsii:b-bfg98m) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/017ec146a6924d6d9939f40346005c7ba570d53a/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L36)):*
> FieldFilterProto

Other codes will only call the `Labeler` or `Model` class in the virtual-people-core repo. These common and util classes are only called by kotlin code I think
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAQt8ib5gSjDovcwPqb:-NAfAZBN0AH6dMrS-lm8:b4ale26) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/017ec146a6924d6d9939f40346005c7ba570d53a/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's fine to have an interface that has no public implementation. That said, I am slightly confused as the documentation says this is a Kotlin version of something called `FieldFilterProto`, which to me sounds like a protobuf message type. Indeed, the factory function takes in a `FieldFilterProto` object so I'm not sure how this can be the Kotlin version of said type.

Looking at the C++ code, it does look like there are indeed concrete implementations of filters e.g. `EqualsFilter`. I assume these would just be private classes with different implementation of `isMatch`. Using a sealed interface would also prevent implementations from being defined outside of this library target.
</blockquote></details>

Thanks

defined as `sealed interface` and `internal` subclasses

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37)* status: all files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @tcsnfkx, @wangyaopw, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAQt8ib5gSjDovcwPqb:-NAfPgagDrT1Ya3jlUon:b681g70) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/017ec146a6924d6d9939f40346005c7ba570d53a/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L36)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

@sanjayvas How to configure this repo to use kotlin 1.5+? I didn't find out how the other repos are setting the version.
</blockquote></details>

The Kotlin language level is [inherited from common-jvm](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/build/versions.bzl). Note that you may need to separately specify this in your IDE settings for it to understand that. e.g. in IntelliJ:


___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAfPDl5CJxkgMdwMrk8:-NAfPDl5CJxkgMdwMrk9:bwswdy8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/5fb98e37bc11a2a3e564df5f374d8f5ba6fee1d7/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L23)):*
> ```Kotlin
> 
> /**
>  * This is the Kotlin implementation of FieldFilterProto.
> ```

Just "Kotlin implementation of ...". See https://developer.android.com/kotlin/style-guide#summary_fragment



_Code quote:_
```Kotlin
 This is the Kotlin
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 24 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAfPLAX0oqPmp8Yb3G_:-NAfPLAX0oqPmp8Yb3Ga:b2xb76f) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/5fb98e37bc11a2a3e564df5f374d8f5ba6fee1d7/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L24)):*
> ```Kotlin
> /**
>  * This is the Kotlin implementation of FieldFilterProto.
>  * @descriptor defines the target protobuf message type this FieldFilter checks.
> ```

The KDoc syntax for this is

```kotlin
* @param descriptor target protobuf message type that this [FieldFilter] checks
```



_Code quote:_
```Kotlin
@descriptor
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/HasFilter.kt` line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAfQpYn2vt7_cTlLMXQ:-NAfQpYn2vt7_cTlLMXR:bb5s9ls) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/5fb98e37bc11a2a3e564df5f374d8f5ba6fee1d7/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/HasFilter.kt#L34)):*
> ```Kotlin
>       error("Name must be set. Input FieldFilterProto: $config")
>     }
>     // TODO(wangyaopw): Build fieldDescriptor from descriptor and config
> ```

Follow TODO format described in [Code Style](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format) doc.

This should be `TODO(@wangyaopw)` if referencing a GitHub username.



_Code quote:_
```Kotlin
wangyaopw
```

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37)* status: 10 of 12 files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @tcsnfkx, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAQt8ib5gSjDovcwPqb:-NAfUwigDYIY5ODShtXP:bc0xzc1) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/017ec146a6924d6d9939f40346005c7ba570d53a/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The Kotlin language level is [inherited from common-jvm](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/build/versions.bzl). Note that you may need to separately specify this in your IDE settings for it to understand that. e.g. in IntelliJ:



</blockquote></details>

Yep, I guessed this comes from common-jvm. But I am not sure how to load the setting to this repo.

The code doesn't build in github action now. Does my workspace miss some lines?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAfPDl5CJxkgMdwMrk8:-NAfTJHY-GSTHhQnf6ZR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/5fb98e37bc11a2a3e564df5f374d8f5ba6fee1d7/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just "Kotlin implementation of ...". See https://developer.android.com/kotlin/style-guide#summary_fragment
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 24 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAfPLAX0oqPmp8Yb3G_:-NAfTYdo7f5XWigXvDPh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/5fb98e37bc11a2a3e564df5f374d8f5ba6fee1d7/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The KDoc syntax for this is

```kotlin
* @param descriptor target protobuf message type that this [FieldFilter] checks
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/HasFilter.kt` line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAfQpYn2vt7_cTlLMXQ:-NAfTga97i6FxqHAfvRQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/5fb98e37bc11a2a3e564df5f374d8f5ba6fee1d7/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/HasFilter.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Follow TODO format described in [Code Style](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format) doc.

This should be `TODO(@wangyaopw)` if referencing a GitHub username.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37)* status: all files reviewed, 1 unresolved discussion (waiting on @tcsnfkx, @wangyaopw, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAQt8ib5gSjDovcwPqb:-NAfjkq08pkJPsgs4_Bv:b-rf391i) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/017ec146a6924d6d9939f40346005c7ba570d53a/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L36)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Yep, I guessed this comes from common-jvm. But I am not sure how to load the setting to this repo.

The code doesn't build in github action now. Does my workspace miss some lines?
</blockquote></details>

You're using an old version of common-jvm (0.35.0) which is before the switch to Kotlin 1.5. The first release that was in was 0.36.0. The newest release is 0.45.0.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @tcsnfkx, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37#-NAQt8ib5gSjDovcwPqb:-NAflDxa-jAzaPydNOkF:b9esh11) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/017ec146a6924d6d9939f40346005c7ba570d53a/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You're using an old version of common-jvm (0.35.0) which is before the switch to Kotlin 1.5. The first release that was in was 0.36.0. The newest release is 0.45.0.
</blockquote></details>

Oh, my bad. Copied pasted from another repo and forgot to check the version

Thank you!

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/37)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx and @wliue)

**Pull request merged**
