### PR TITLE
Update AnyInFilter to use generic subclasses.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/48)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/48)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt` line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/48#-NBJOifj646gcSOSvgs2:-NBJOifj646gcSOSvgs3:bp253cm) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7feeaa36ac4a984ddcf21e5a777403e26b4a7766/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt#L83)):*
> ```Kotlin
> 
> /** Implementation of AnyFilter for [ValueType]. */
> internal class AnyInFilterImpl<ValueType>(
> ```

nit: `V`

See https://developer.android.com/kotlin/style-guide#type_variable_names



_Code quote:_
```Kotlin
ValueType
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt` line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/48#-NBJPk131nBlEwzYdTZk:-NBJPk131nBlEwzYdTZl:b-kc9owg) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7feeaa36ac4a984ddcf21e5a777403e26b4a7766/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt#L89)):*
> ```Kotlin
> 
>   override fun matches(messageOrBuilder: MessageOrBuilder): Boolean {
>     val values =
> ```

Specify types explicitly unless it's obvious (e.g. assigning from a constructor or well-known factory function).
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt` line 101 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/48#-NBJQ2OrAoPBBPbECyRa:-NBJQ2OsEDcPXwgZc_mn:b-mtpqr4) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7feeaa36ac4a984ddcf21e5a777403e26b4a7766/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt#L101)):*
> ```Kotlin
>         else -> error("Unsupported field type for ANY_IN filter. ${fieldDescriptors.last().type}")
>       }
>     values.forEach {
> ```

nit: I think this can be rewritten more succinctly as `values.any { parsedValues.contains(it) }` 
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt` line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/48#-NBJPRRsAgq4fGQuUDnX:-NBJPRRsAgq4fGQuUDnY:b-6nyzou) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7feeaa36ac4a984ddcf21e5a777403e26b4a7766/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt#L104)):*
> ```Kotlin
>       @Suppress("UNCHECKED_CAST")
>       // Guaranteed safe since all types come from the same fieldDescriptor.type
>       if (parsedValues.contains(it as ValueType)) {
> ```

I think the cast is in the wrong place here: I think the type of `values` is `List<Any>`, where it should instead be `List<ValueType>`.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/48)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt` line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/48#-NBJOifj646gcSOSvgs2:-NBJf9Go8I1r7uhjg7wB:b-1lqkdw) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7feeaa36ac4a984ddcf21e5a777403e26b4a7766/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt#L83)):*
> https://developer.android.com/kotlin/style-guide#type_variable_names
done
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt` line 101 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/48#-NBJQ2OrAoPBBPbECyRa:-NBJffZQ2s5lGqQJZlUe:b-7g7psf) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7feeaa36ac4a984ddcf21e5a777403e26b4a7766/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt#L101)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: I think this can be rewritten more succinctly as `values.any { parsedValues.contains(it) }` 
</blockquote></details>

yep. 
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt` line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/48#-NBJPRRsAgq4fGQuUDnX:-NBJgyv172HeWCpjHOzV:b-ma1i6e) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7feeaa36ac4a984ddcf21e5a777403e26b4a7766/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think the cast is in the wrong place here: I think the type of `values` is `List<Any>`, where it should instead be `List<ValueType>`.
</blockquote></details>

It is not wrong, just casting at different places.

1. values is List<Any> , we cast each element to ValueType and see if parsedValues contains it or not
2. value is casted to List<ValueType>, we check if parsedValues contains each element or not

Updated from 1 to 2.



_Code quote:_
```Kotlin
/ Guaranteed safe since all types come from the same fieldDescriptor.type
```

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/48)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt` line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/48#-NBJPk131nBlEwzYdTZk:-NBJi6Zq4IAz79p_wAFn:b-jenqvn) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7feeaa36ac4a984ddcf21e5a777403e26b4a7766/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt#L89)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Specify types explicitly unless it's obvious (e.g. assigning from a constructor or well-known factory function).
</blockquote></details>

Done.

Added casting at the end. so it is now obvious

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 4 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 4 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/48)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
