### PR TITLE
Migrate to Bzlmod.

### PR DESCRIPTION
**Pull request by SanjayVas**
This drops the dependency on common-jvm, instead depending on rules_kotlin_jvm directly.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/65)

**Review by SanjayVas — COMMENTED** [review]
Depends on world-federation-of-advertisers/rules_kotlin_jvm#2

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/65#-:-Nm7yfkb680Ak9_KJiqr:b5domjv)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[`.bazelrc` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/65#-Nm7ySTe-adxNsY8o_Bj:-Nm7ySTe-adxNsY8o_Bk:b-d209wn) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/8ba649ae478d2f0840dd7e7047f05667bd2b44b4/.bazelrc#L15)):*
> ```
> build --java_runtime_version=remotejdk_11
> 
> # Target Java 9.
> ```

FYI java_language_version=8 is now deprecated by the Kotlin compiler

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 11 of 13 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/65)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 7 of 13 files at r1, 1 of 2 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/65)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
