### PR TITLE
Move tests to src/test.

### PR DESCRIPTION
**Pull request by tcsnfkx**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/18)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/18)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/test/cc/wfa/virtual_people/common/field_filter/test/BUILD.bazel, line 6 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/18#-Mf3cyJF4Ukb_pvPKK2v:-Mf3cyJF4Ukb_pvPKK2w:bpcr8q9) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/aeeccb9f5fe0563892c29efd4109b82a0576d51a/src/test/cc/wfa/virtual_people/common/field_filter/test/BUILD.bazel#L6)):*
> ```Starlark
> package(default_visibility = ["//src/test/cc/wfa/virtual_people/common/field_filter:__subpackages__"])
> 
> proto_library(
> ```

I'm wondering if this should just live in `//src/main/proto/wfa/virtual_people/common/test.proto`

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/18)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/test/cc/wfa/virtual_people/common/field_filter/test/BUILD.bazel, line 6 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/18#-Mf3cyJF4Ukb_pvPKK2v:-Mf4E8kMDu45w34cb5GB:bg1totw) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/aeeccb9f5fe0563892c29efd4109b82a0576d51a/src/test/cc/wfa/virtual_people/common/field_filter/test/BUILD.bazel#L6)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm wondering if this should just live in `//src/main/proto/wfa/virtual_people/common/test.proto`
</blockquote></details>

I think it makes more sense to be in src/test, as this is only used in tests.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/18)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

**Review by wliue — APPROVED** [review]
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/18)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, and @oliver-amzn)

**Review by mpatel24 — APPROVED** [review]

**Review by efoxepstein — APPROVED** [review]
> Reviewed 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/18)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, and @oliver-amzn)

**Review by wliue — APPROVED** [review]
> Reviewed 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/18)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, and @oliver-amzn)

**Pull request merged**
