### PR TITLE
Integer Comparator util

### PR DESCRIPTION
**Pull request by JuliethHernandez**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @JuliethHernandez and @wangyaopw)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNds6Q7EOfKN-Hze8c:-NBNds6Q7EOfKN-Hze8d:bvh0etk) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L48)):*
> ```Kotlin
>  * = IntegerComparator.new(fieldDescriptors, "10")
>  *
>  * Compare examples: testProto1 = testProto { a = testProtoA { b = testProtoB { value = 11 } } }
> ```

make these code block using ```



_Code quote:_
```Kotlin
 * Compare examples: testProto1 = testProto { a = testProtoA { b = testProtoB { value = 11 } } }
 * IntegerCompareResult result1 = comparator.compare(testProto1); GREATER_THAN
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNe2eWEvBGzssu8S9s:-NBNe2eWEvBGzssu8S9t:bf7jj57) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L56)):*
> ```Kotlin
>  * testProto3 = testProto { a = testProtoA { b = testProtoB { value = 9 } } } IntegerCompareResult
>  * result3 = comparator.compare(testProto3); LESS_THAN
>  */
> ```

The comment is not for `IntegerCompareResult`, move it above the class



_Code quote:_
```Kotlin
 */
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNeOBeD5D0_tlWqa4e:-NBNeOBf7WtYjbAwPIsa:b-q6vlym) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L75)):*
> ```Kotlin
>    */
>   abstract fun compare(messageOrBuilder: MessageOrBuilder): IntegerCompareResult
>   companion object {
> ```

add an empty above `companion object`
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNeljz0SR9Dz00x4v3:-NBNeljz0SR9Dz00x4v4:b-8a2bp6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L79)):*
> ```Kotlin
>      * Always use [IntegerComparator.new] to get an [IntegerComparator] object.
>      *
>      * Returns error status if any of the following happens:
> ```

status is for C++

here we say "Throws an error"



_Code quote:_
```Kotlin
 Returns error status 
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNfG-U7FtRJPeIcvYF:-NBNfG-U7FtRJPeIcvYG:b-7sph4b) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L102)):*
> ```Kotlin
> }
> 
> private class IntegerComparatorImpl<ValueType>(
> ```

Replace ValueType with T

also update the MessageFiltlerUtil   (The other files are handled by me in https://github.com/world-federation-of-advertisers/virtual-people-common/pull/48)



_Code quote:_
```Kotlin
ValueType
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 106 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNf7Wu38QyhZIzixCj:-NBNf7Wu38QyhZIzixCk:b6y9kns) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L106)):*
> ```Kotlin
>   val value: ValueType
> ) : IntegerComparator(fieldDescriptors) {
>   @Suppress("UNCHECKED_CAST")
> ```

nit: add an empty line above this function



_Code quote:_
```Kotlin
@Suppress("UNCHECKED_CAST")
```
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/BUILD.bazel` line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNfuT13ULdzYKa_Mz_:-NBNfuT13ULdzYKa_Mza:bl82lpf) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/BUILD.bazel#L71)):*
> ```Starlark
>         "//src/main/proto/wfa/virtual_people/common/field_filter/test:test_kt_jvm_proto",
>         "@wfa_common_jvm//imports/java/com/google/common/truth",
>         "@wfa_common_jvm//imports/java/com/google/common/truth/extensions/proto",
> ```

you don't need some of this. delete them 1 by 1 to see if it still build.



_Code quote:_
```Starlark
        "@wfa_common_jvm//imports/java/com/google/common/truth",
        "@wfa_common_jvm//imports/java/com/google/common/truth/extensions/proto",
        "@wfa_common_jvm//imports/java/com/google/protobuf/util",
```
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt` line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNgB_OCF4GHBO_Xyl9:-NBNgB_P7ca6FsUM2ANj:bqr4h21) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt#L39)):*
> ```Kotlin
>     /** "1l" is not a valid int32. */
>     val fieldDescriptors = getFieldFromProto(TestProto.getDescriptor(), "a.b.int32_value")
>     assertFailsWith<NumberFormatException> { IntegerComparator.new(fieldDescriptors, "1l") }
> ```

nit: for l it is better to use big letter L. It is more obvious it is L not one



_Code quote:_
```Kotlin
1l
```
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNgdFCEEUbfyNcO2F4:-NBNgdFCEEUbfyNcO2F5:blrlopd) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt#L43)):*
> ```Kotlin
> 
>   @Test
>   fun `float value`() {
> ```

`value type mismatch should throw`



_Code quote:_
```Kotlin
float value
```

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @JuliethHernandez and @wangyaopw)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNds6Q7EOfKN-Hze8c:-NBO805Q-3iE4gLT0_5T:b-77x0q5) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L48)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

make these code block using ```
</blockquote></details>

Move "Compare examples: " outside the block , and add // before GREATER_THAN, EQUAL, LESS_THAN



_Code quote:_
```Kotlin
Compare examples: 
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNfG-U7FtRJPeIcvYF:-NBO8XRO0PIb1tmpLa4E:btmtwst) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L102)):*
> MessageFiltlerUtil 
Still need to update MessageFiltlerUtil 
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNgdFCEEUbfyNcO2F4:-NBO8NWt4KPyYCvQbls0:b-owpj85) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt#L43)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

`value type mismatch should throw`
</blockquote></details>

The point is "value type mismatch" should match

**Review by JuliethHernandez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @wangyaopw)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNds6Q7EOfKN-Hze8c:-NBNxgp6-BTLTPiym5My:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L48)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

make these code block using ```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNe2eWEvBGzssu8S9s:-NBNyTIiAV_yLG-NdSae:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L56)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

The comment is not for `IntegerCompareResult`, move it above the class
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNeOBeD5D0_tlWqa4e:-NBNyiDj-unCUK8toZeo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L75)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

add an empty above `companion object`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNeljz0SR9Dz00x4v3:-NBNyrTe9Za2dZrX8EOw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L79)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

status is for C++

here we say "Throws an error"
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNfG-U7FtRJPeIcvYF:-NBNzGDTE_MlYbwObVf2:b5ircyd) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L102)):*
> ValueType
Ok, but there is no ValueType in MessageFilterUtil
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/BUILD.bazel` line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNfuT13ULdzYKa_Mz_:-NBO-g2w8WG1hbmntqAL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/BUILD.bazel#L71)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

you don't need some of this. delete them 1 by 1 to see if it still build.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNgdFCEEUbfyNcO2F4:-NBO-xuv9CZcxoobSV8-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt#L43)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

`value type mismatch should throw`
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @JuliethHernandez and @wangyaopw)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNds6Q7EOfKN-Hze8c:-NBOtKbQ80rFSI_spGN4:bms52h5) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L48)):*
<details><summary><i>Previously, JuliethHernandez (Angela Julieth Hernández Cáceres) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

comparator = IntegerComparator.new(fieldDescriptors, "10") is also inside 



_Suggestion:_
```Kotlin
 * comparator = IntegerComparator.new(fieldDescriptors, "10")
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBNfG-U7FtRJPeIcvYF:-NBOtWPM8xu786fMMgjS:b-q8lwlw) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e54852b3aa9359c54402ca1b4da98fc58ede7fd8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L102)):*
<details><summary><i>Previously, JuliethHernandez (Angela Julieth Hernández Cáceres) wrote…</i></summary><blockquote>

> ValueType
Ok, but there is no ValueType in MessageFilterUtil
</blockquote></details>

oh, that is nice

**Review by wliue — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49)* status: all files reviewed, 3 unresolved discussions (waiting on @JuliethHernandez and @tcsnfkx)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 60 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBP3ZVI74mWq5sWCmYr:-NBP3ZVJ-rJD3LYu5DN5:bnt2cm4) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/d329ba11e377639b11a68fa74d1563f037fc4030/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L60)):*
> ```Kotlin
>  * IntegerCompareResult result1 = comparator.compare(testProto1); // GREATER_THAN
>  *
>  * testProto2 = testProto { a = testProtoA { b = testProtoB { value = 10 } } } IntegerCompareResult
> ```

Should this be on next line?



_Code quote:_
```Kotlin
IntegerCompareResult
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 63 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBP3gEd8JRcF7wZuN53:-NBP3gEd8JRcF7wZuN54:bnt2cm4) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/d329ba11e377639b11a68fa74d1563f037fc4030/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L63)):*
> ```Kotlin
>  * result2 = comparator.compare(testProto2); // EQUAL
>  *
>  * testProto3 = testProto { a = testProtoA { b = testProtoB { value = 9 } } } IntegerCompareResult
> ```

Should this be on next line?



_Code quote:_
```Kotlin
IntegerCompareResult
```

**Review by JuliethHernandez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49)* status: all files reviewed, 3 unresolved discussions (waiting on @JuliethHernandez, @tcsnfkx, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 60 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBP3ZVI74mWq5sWCmYr:-NBS_E6W7aEC710PrCWz:bafqqkw) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/d329ba11e377639b11a68fa74d1563f037fc4030/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L60)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Should this be on next line?
</blockquote></details>

Yes, thanks :)

**Review by JuliethHernandez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @JuliethHernandez, @tcsnfkx, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt` line 63 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49#-NBP3gEd8JRcF7wZuN53:-NBSaAiF72f3neEVyA95:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/d329ba11e377639b11a68fa74d1563f037fc4030/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt#L63)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Should this be on next line?
</blockquote></details>

Done.

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49)* status: all files reviewed, 1 unresolved discussion (waiting on @tcsnfkx and @wangyaopw)

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx)

**Pull request merged**
