### PR TITLE
Message filter util implementation

### PR DESCRIPTION
**Pull request by JuliethHernandez**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @JuliethHernandez and @wangyaopw)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtil.kt` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46#-NB-GWc5D14tg1NNOnxp:-NB-GWc5D14tg1NNOnxq:bb6ht37) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/b9a8d1277186238a473997d940b5624d8167cbc8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtil.kt#L1)):*
> ```Kotlin
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

2022
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtil.kt` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46#-NB-Hwml3kUATZpke74t:-NB-Hwml3kUATZpke74u:b-hqtukd) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/b9a8d1277186238a473997d940b5624d8167cbc8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtil.kt#L23)):*
> ```Kotlin
> import org.wfanet.virtualpeople.common.fieldFilterProto
> 
> private val supportedType =
> ```

Type.MESSAGE is also supported



_Code quote:_
```Kotlin
supportedType
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtil.kt` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46#-NB-H9SQ2sbaeEz38K6s:-NB-H9SQ2sbaeEz38K6t:b-vcu3do) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/b9a8d1277186238a473997d940b5624d8167cbc8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtil.kt#L27)):*
> ```Kotlin
> 
> /**
>  * Convert the protobuf field in @param message represented by fieldDescriptor to a
> ```

Kotlin comment style is like

```
/**
 * Convert the protobuf field in [message] represented by [fieldDescriptor] to
 * a [FieldFilterProto], which checks the equality of the given field, or any
 * nested field of the given field.
 *
 */
```



_Code quote:_
```Kotlin
/**
 * Convert the protobuf field in @param message represented by fieldDescriptor to a
 * FieldFilterProto, which checks the equality of the given field, or any nested field of the given
 * field.
 */
```
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtil.kt` line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46#-NB-I5XF84gTiVGC4B2u:-NB-I5XG-9nObEgQL0pl:b-8uzsfu) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/b9a8d1277186238a473997d940b5624d8167cbc8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtil.kt#L39)):*
> ```Kotlin
>   }
> 
>   return fieldFilterProto {
> ```

```
 if (fieldDescriptor.type !in supportedType) {
    error("Unsupported field type converting to FieldFilterProto from: $message")
}
  return fieldFilterProto {
    name = fieldDescriptor.name
    if (fieldDescriptor.type == Type.MESSAGE) {
      op = FieldFilterProto.Op.PARTIAL
      subFilters.add(convertMessageToFilter(message.getField(fieldDescriptor) as MessageOrBuilder))
    } else {
      op = FieldFilterProto.Op.EQUAL
      value = message.getField(fieldDescriptor).toString()
    }
  }

```



_Code quote:_
```Kotlin
  return fieldFilterProto {
    name = fieldDescriptor.name
    op = FieldFilterProto.Op.EQUAL
    if (fieldDescriptor.type == Type.MESSAGE) {
      op = FieldFilterProto.Op.PARTIAL
      subFilters.add(convertMessageToFilter(message.getField(fieldDescriptor) as MessageOrBuilder))
    } else if (fieldDescriptor.type in supportedType) {
      value = message.getField(fieldDescriptor).toString()
    } else {
      error("Unsupported field type converting to FieldFilterProto from: $message")
    }
  }
```
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtilTest.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46#-NB-IpxP8j2o1DdndCk7:-NB-IpxQ9ueGsypi4cLa:bb6h4m0) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/b9a8d1277186238a473997d940b5624d8167cbc8/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtilTest.kt#L36)):*
> ```Kotlin
>   @Test
>   fun `float not supported should throw`() {
>     val filterMessage = testProto { a = testProtoA { b = testProtoB { floatValue = 1.0F } } }
> ```

1.0f



_Code quote:_
```Kotlin
1.0F
```
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtilTest.kt` line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46#-NB-J70E-OthbKc-uTtW:-NB-J70E-OthbKc-uTtX:b-4yojd7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/b9a8d1277186238a473997d940b5624d8167cbc8/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtilTest.kt#L51)):*
> ```Kotlin
>       a = testProtoA {
>         b = testProtoB {
>           int32Value = 1
> ```

only keep `int32Values.add(1)`

Try our best to match the c++ tests exactly



_Code quote:_
```Kotlin
          int32Value = 1
          int32Values.add(1)
          int32Values.add(2)
          int32Values.add(3)
```
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtilTest.kt` line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46#-NB-JUYSDwjcD-953OXv:-NB-JUYSDwjcD-953OXw:b-b1zhja) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/b9a8d1277186238a473997d940b5624d8167cbc8/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtilTest.kt#L80)):*
> ```Kotlin
>       subFilters.add(
>         fieldFilterProto {
>           op = FieldFilterProto.Op.PARTIAL
> ```

import FieldFilterProto.Op, so you don't need so many "FieldFilterProto." in the code



_Code quote:_
```Kotlin
FieldFilterProto.Op
```
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtilTest.kt` line 148 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46#-NB-JsoaAQa63hUoUwD2:-NB-Jsob0iZqjcAnLnhp:b-v93m2y) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/b9a8d1277186238a473997d940b5624d8167cbc8/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtilTest.kt#L148)):*
> ```Kotlin
>   @Test
>   fun `bool True suported`() {
>     val filter = fieldFilterProto {
> ```

`val expectedFilter`

same for other tests



_Code quote:_
```Kotlin
filter 
```

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @JuliethHernandez and @wangyaopw)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtil.kt` line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46#-NB-I5XF84gTiVGC4B2u:-NBDi8if0Tjyu86QHUUr:beolph4) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/b9a8d1277186238a473997d940b5624d8167cbc8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtil.kt#L39)):*
<details><summary><i>Previously, JuliethHernandez (Angela Julieth Hernández Cáceres) wrote…</i></summary><blockquote>

> op = FieldFilterProto.Op.EQUAL
right, but this line should be after name, no ? Equal is always set, also in message type. 
</blockquote></details>

When type is MESSAGE, op is PARTIAL, not EQUAL.

EQUAL is for cases other than MESSAGE, so it should be in the else if {}
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtilTest.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46#-NB-IpxP8j2o1DdndCk7:-NBDilaC1xmirYmxwv2b:b-xv3tsf) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/b9a8d1277186238a473997d940b5624d8167cbc8/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtilTest.kt#L36)):*
<details><summary><i>Previously, JuliethHernandez (Angela Julieth Hernández Cáceres) wrote…</i></summary><blockquote>

why in lower case? 
</blockquote></details>

both f and F work. But we are already using f in our codebase. so it is better to keep consistent.

https://kotlinlang.org/docs/numbers.html#floating-point-types
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtilTest.kt` line 148 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46#-NB-JsoaAQa63hUoUwD2:-NBDjCj059bOxmZXhJ-E:bro543s) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/b9a8d1277186238a473997d940b5624d8167cbc8/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtilTest.kt#L148)):*
<details><summary><i>Previously, JuliethHernandez (Angela Julieth Hernández Cáceres) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done yet. There are still several tests using `filter` not `expectedFilter`

**Review by JuliethHernandez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @JuliethHernandez and @wangyaopw)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtil.kt` line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46#-NB-I5XF84gTiVGC4B2u:-NBIXmY05j2VSvdmBp60:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/b9a8d1277186238a473997d940b5624d8167cbc8/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtil.kt#L39)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

When type is MESSAGE, op is PARTIAL, not EQUAL.

EQUAL is for cases other than MESSAGE, so it should be in the else if {}
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JuliethHernandez)

**Review by tcsnfkx — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wliue)

**Pull request merged**
