### PR TITLE
Gt Filter and Lt Filter

### PR DESCRIPTION
**Pull request by JuliethHernandez**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51)

### CODE REVIEW

**Review by JuliethHernandez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/GtFilterTest.kt` line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51#-NBTCIdg6wnTSLTPIFhh:-NBmJDZP7beYF5bgH8wb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/bb69055913e6840e6b808d007f7a24d52b3438f6/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/GtFilterTest.kt#L53)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Please assert exception message like line 43 if possible for all the rest tests and for all future tests.

We have some early tests that don't check the message, we'll update those later.
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx and @wliue)

**Review by wangyaopw — APPROVED** [review]
> Reviewed 5 of 5 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx and @wliue)

**Review by wliue — APPROVED** [review]
> Reviewed 5 of 5 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51)* status: all files reviewed, 7 unresolved discussions (waiting on @JuliethHernandez and @tcsnfkx)

___
*[`-- commits` line 2 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51#-NBnRaQHEzTQA6COLTSA):*
Nit: -> and



_Code quote:_
```
- ff116a2: gt an lt filter
```
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/GtFilterTest.kt` line 47 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51#-NBnSJMiDdIFs4a7cOud:-NBnSJMiDdIFs4a7cOue:b-bykzvb) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ff116a2a5ea1c934936b224c72041017932b2c7a/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/GtFilterTest.kt#L47)):*
> ```Kotlin
> 
>   @Test
>   fun `no integer field should fail`() {
> ```

Nit: no -> not



_Code quote:_
```Kotlin
no
```
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/GtFilterTest.kt` line 61 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51#-NBnSQoDCufMmBUV-z5v:-NBnSQoDCufMmBUV-z5w:b-807afv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ff116a2a5ea1c934936b224c72041017932b2c7a/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/GtFilterTest.kt#L61)):*
> ```Kotlin
> 
>   @Test
>   fun `disallowed reppeated should fail`() {
> ```

Typo.
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/GtFilterTest.kt` line 75 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51#-NBnSSR0ArLwjXYfEuFa:-NBnSSR0ArLwjXYfEuFb:b-807afv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ff116a2a5ea1c934936b224c72041017932b2c7a/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/GtFilterTest.kt#L75)):*
> ```Kotlin
> 
>   @Test
>   fun `disallowed reppeated in the path should fail`() {
> ```

Typo.
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/LtFilterTest.kt` line 46 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51#-NBnSrvv-oo5Q6Travdo:-NBnSrvv-oo5Q6Travdp:b-bykzvb) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ff116a2a5ea1c934936b224c72041017932b2c7a/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/LtFilterTest.kt#L46)):*
> ```Kotlin
> 
>   @Test
>   fun `no integer field should fail`() {
> ```

Nit: no -> not
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/LtFilterTest.kt` line 60 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51#-NBnSuTe7wbGExchAXo7:-NBnSuTe7wbGExchAXo8:b-807afv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ff116a2a5ea1c934936b224c72041017932b2c7a/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/LtFilterTest.kt#L60)):*
> ```Kotlin
> 
>   @Test
>   fun `disallowed reppeated should fail`() {
> ```

Typo.
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/LtFilterTest.kt` line 74 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51#-NBnSviMBT5E89xc7Ysa:-NBnSviMBT5E89xc7Ysb:b-807afv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ff116a2a5ea1c934936b224c72041017932b2c7a/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/LtFilterTest.kt#L74)):*
> ```Kotlin
> 
>   @Test
>   fun `disallowed reppeated in the path should fail`() {
> ```

Typo.

**Review by JuliethHernandez — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51)* status: 4 of 10 files reviewed, all discussions resolved (waiting on @tcsnfkx, @wangyaopw, and @wliue)

___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/LtFilterTest.kt` line 74 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51#-NBnSviMBT5E89xc7Ysa:-NBncQCS4FAqe6Jv8Mgl:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ff116a2a5ea1c934936b224c72041017932b2c7a/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/LtFilterTest.kt#L74)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Typo.
</blockquote></details>

Done

**Review by tcsnfkx — APPROVED** [review]
> Reviewed 3 of 5 files at r4, 1 of 1 files at r6, 2 of 6 files at r7, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JuliethHernandez)

**Pull request merged**
