### PR TITLE
Create a library to set field in protobuf messages using reflection.

### PR DESCRIPTION
**Pull request by tcsnfkx**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15)

### CODE REVIEW

**Review by wliue — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 101 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15#-McKP7FJ5YgBo85o1rq7:-McKP7FJ5YgBo85o1rq8:byuv5lq) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/dbee44a2c626806e75aabf764551a3a262156739/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L101)):*
> ```objc
> // The field must be an immediate field of @message.
> // The corresponding C++ type of the field must be @ValueType.
> template <typename ValueType>
> ```

Which types are valid?
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 168 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15#-McKPfSP3leSc2WOu-fN:-McKPfSP3leSc2WOu-fO:b9rfmvn) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/dbee44a2c626806e75aabf764551a3a262156739/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L168)):*
> ```objc
> //   optional MsgB b = 1;
> // }
> // To get the field descriptors of MsgA.b.c, the call is
> ```

Nit: -> To get the field descriptors of MsgA.b.c:
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 172 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15#-McKPlZY62sUQy-iCRa5:-McKPlZY62sUQy-iCRa6:b3hkpik) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/dbee44a2c626806e75aabf764551a3a262156739/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L172)):*
> ```
> // And if there is a MsgA object obj_a, to set the value of obj_a.b.c to 10, the
> // call is
> ```

Nit: -> And if there is a MsgA object obj_a, to set the value of obj_a.b.c to 10:
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util_test.cc, line 191 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15#-McKTj4K64-hHMu3FCaW:-McKTj4L7x28lWDbLR37:b-okoys5) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/dbee44a2c626806e75aabf764551a3a262156739/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util_test.cc#L191)):*
> ```cpp
> }
> 
> TEST(FieldUtilTest, GetFieldAndSetValue) {
> ```

Add a test that set value on a top level field, e.g. "a.int32_value".

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15)* status: all files reviewed, 5 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 101 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15#-McKP7FJ5YgBo85o1rq7:-McKi8664TUzgYLF9NH2:bwfvllj) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/dbee44a2c626806e75aabf764551a3a262156739/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L101)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Which types are valid?
</blockquote></details>

Maybe add a:

```
template <typename ValueType, absl::enable_if<absl::disjuction<std::is_same<ValueType, int>, std::is_same<ValueType, double>, ...>>
```

to enforce what's supported.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.cc, line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15#-McKihwE6UVqFJUMTcob:-McKihwF62oWhV3pEWxw:b-8etoec) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/dbee44a2c626806e75aabf764551a3a262156739/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.cc#L80)):*
> ```cpp
>         field_descriptors) {
>   google::protobuf::Message* tmp_message = &message;
>   for (auto it = field_descriptors.begin(), j = field_descriptors.end() - 1;
> ```

Maybe worth adding a comment for why the last `field_descriptors` entry is unused?

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 101 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15#-McKP7FJ5YgBo85o1rq7:-McL15sb93nzKRCiMx7V:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/dbee44a2c626806e75aabf764551a3a262156739/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L101)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe add a:

```
template <typename ValueType, absl::enable_if<absl::disjuction<std::is_same<ValueType, int>, std::is_same<ValueType, double>, ...>>
```

to enforce what's supported.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 168 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15#-McKPfSP3leSc2WOu-fN:-McL19c4606EA0swnLvF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/dbee44a2c626806e75aabf764551a3a262156739/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L168)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Nit: -> To get the field descriptors of MsgA.b.c:
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 172 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15#-McKPlZY62sUQy-iCRa5:-McL1BEK3P7Dj4-IqGB3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/dbee44a2c626806e75aabf764551a3a262156739/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L172)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
> // And if there is a MsgA object obj_a, to set the value of obj_a.b.c to 10, the
> // call is
> ```

Nit: -> And if there is a MsgA object obj_a, to set the value of obj_a.b.c to 10:
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.cc, line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15#-McKihwE6UVqFJUMTcob:-McL1Es12eIptLDGiuzy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/dbee44a2c626806e75aabf764551a3a262156739/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.cc#L80)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe worth adding a comment for why the last `field_descriptors` entry is unused?
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util_test.cc, line 191 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15#-McKTj4K64-hHMu3FCaW:-McL1GWQC1ucWWaXtUN4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/dbee44a2c626806e75aabf764551a3a262156739/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util_test.cc#L191)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Add a test that set value on a top level field, e.g. "a.int32_value".
</blockquote></details>

Done.

**Review by wliue — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15)* status: all files reviewed, 3 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 91 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15#-McLumxJ3MW316EuH156:-McLumxJ3MW316EuH157:b-jlxrsk) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/745018698107f4c8864728035182240008bfe599/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L91)):*
> ```objc
> // The field must be an immediate field of @message.
> // The corresponding C++ type of the field must be @ValueType.
> template <typename ValueType, absl::enable_if_t<absl::disjunction<
> ```

I think you might be able to pull this out for reuse:

```
template <typename ValueType>
using EnableIfProtoType = absl::enable_if_t<...>;

template <typename ValueType,  typename = EnableIfProtoType<ValueTyle>>
ValueType GetFoo(...);
```

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 91 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15#-McLumxJ3MW316EuH156:-McNRUJV29xpHbxHe1PI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/745018698107f4c8864728035182240008bfe599/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L91)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think you might be able to pull this out for reuse:

```
template <typename ValueType>
using EnableIfProtoType = absl::enable_if_t<...>;

template <typename ValueType,  typename = EnableIfProtoType<ValueTyle>>
ValueType GetFoo(...);
```
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15)* status: all files reviewed, 3 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 28 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15#-McPBD6n5qmTYbkL54gY:-McPBD6o4LoMRXjuG_Zd:b-ji9kyq) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/bc199df5450eccb3b5e5a423b00bc4396ef471f9/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L28)):*
> ```objc
> template <typename ValueType>
> using EnableIfProtoType = absl::enable_if_t<absl::disjunction<
>     std::is_same<ValueType, int32_t>,
> ```

If you want to consolidate more, you could write something like:

```
template <typename ValueType>
using EnableIfProtoType = absl::enable_if_t<absl::disjunction<
  EnableIfProtoValueType::value,
  std::is_same<ValueType, const google::protobuf::Message&>::value, bool>;
```

**Review by wliue — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15)* status: all files reviewed, 3 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 28 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15#-McPBD6n5qmTYbkL54gY:-McSX_6VBAaGaRKOaenp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/bc199df5450eccb3b5e5a423b00bc4396ef471f9/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

If you want to consolidate more, you could write something like:

```
template <typename ValueType>
using EnableIfProtoType = absl::enable_if_t<absl::disjunction<
  EnableIfProtoValueType::value,
  std::is_same<ValueType, const google::protobuf::Message&>::value, bool>;
```
</blockquote></details>

Done.

**Review by mpatel24 — APPROVED** [review]

**Pull request merged**
