### PR TITLE
Implement IN and ANY_IN field filter

### PR DESCRIPTION
**Pull request by tcsnfkx**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16)* status: all files reviewed, 5 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter.cc, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-Md7571WD68bRMH6le_i:-Md7571WD68bRMH6le_j:b89995t) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/298352af3a7dc900ba379590da69066ecdf4fc0a/src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter.cc#L43)):*
> ```cpp
> //   const std::string&
> template <typename ValueType>
> class AnyInFilterImpl : public AnyInFilter {
> ```

Can this be in an anonymous namespace? (Along with everything else not declared in the header)
___
*[src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter.cc, line 63 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-Md75OEn9lUkcffvNmN4:-Md75OEn9lUkcffvNmN5:b-968qpm) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/298352af3a7dc900ba379590da69066ecdf4fc0a/src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter.cc#L63)):*
> ```cpp
>   for (int i = 0; i < size; ++i) {
>     if (parser_.values.find(GetValueFromRepeatedProto<ValueType>(
>             message, field_descriptors_, i)) != parser_.values.end()) {
> ```

Could you split this statement up into two for clarity?

```
const ValueType& value = GetValueFromRepeatedProto<ValueType>(...);
if (...) {
```
___
*[src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter.cc, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-Md75r2H7RDlorqxSTYI:-Md75r2H7RDlorqxSTYJ:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/298352af3a7dc900ba379590da69066ecdf4fc0a/src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter.cc#L75)):*
> ```cpp
>   int size = GetSizeOfRepeatedProto(message, field_descriptors_);
>   for (int i = 0; i < size; ++i) {
>     if (parser_.values.find(GetValueFromRepeatedProto<
> ```

Ditto
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/template_util.h, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-Md77osq48J_edhR5n4c:-Md77osq48J_edhR5n4d:b-374aps) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/298352af3a7dc900ba379590da69066ecdf4fc0a/src/main/cc/wfa/virtual_people/common/field_filter/utils/template_util.h#L22)):*
> ```objc
> #include "google/protobuf/message.h"
> 
> namespace wfa_virtual_people {
> ```

Can you add a comment for this file explaining the basic idea and how to use these?
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/values_parser.h, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-Md788Dz8KqyfuvNAz1X:-Md788Dz8KqyfuvNAz1Y:b104qg0) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/298352af3a7dc900ba379590da69066ecdf4fc0a/src/main/cc/wfa/virtual_people/common/field_filter/utils/values_parser.h#L30)):*
> ```objc
> 
> template <typename ValueType, EnableIfNonFloatProtoValueType<ValueType> = true>
> struct ValuesParser {
> ```

I don't quite follow how this is a parser, can you explain? (From usage, it looks more like `ParsedValues` perhaps?)

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16)* status: 17 of 23 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter.cc, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-Md7571WD68bRMH6le_i:-MdKqGH-BEQT8D6AXVjK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/298352af3a7dc900ba379590da69066ecdf4fc0a/src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter.cc#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can this be in an anonymous namespace? (Along with everything else not declared in the header)
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter.cc, line 63 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-Md75OEn9lUkcffvNmN4:-MdKqHma2oNjaBHp_-0-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/298352af3a7dc900ba379590da69066ecdf4fc0a/src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter.cc#L63)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Could you split this statement up into two for clarity?

```
const ValueType& value = GetValueFromRepeatedProto<ValueType>(...);
if (...) {
```
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter.cc, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-Md75r2H7RDlorqxSTYI:-MdKqItI4quWiRuhhhG3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/298352af3a7dc900ba379590da69066ecdf4fc0a/src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter.cc#L75)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/template_util.h, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-Md77osq48J_edhR5n4c:-MdKqKTr2JpcUmgXiQM1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/298352af3a7dc900ba379590da69066ecdf4fc0a/src/main/cc/wfa/virtual_people/common/field_filter/utils/template_util.h#L22)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you add a comment for this file explaining the basic idea and how to use these?
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/values_parser.h, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-Md788Dz8KqyfuvNAz1X:-MdKqLrU34jOxmAexM0A:bfkjxe8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/298352af3a7dc900ba379590da69066ecdf4fc0a/src/main/cc/wfa/virtual_people/common/field_filter/utils/values_parser.h#L30)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't quite follow how this is a parser, can you explain? (From usage, it looks more like `ParsedValues` perhaps?)
</blockquote></details>

Updated the name of the struct and the factory functions.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

**Review by mpatel24 — APPROVED** [review]

**Review by wliue — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16)* status: all files reviewed, 9 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter_test.cc, line 293 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXtcU97UHHbWeKe40I:-MdXtcU97UHHbWeKe40J:b-l14gk6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter_test.cc#L293)):*
> ```cpp
> }
> 
> TEST(AnyInFilterTest, TestEnumNumber) {
> ```

Could add a test for mix of enum value/number.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter_test.cc, line 335 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXm6ia3pf58BfJhtLP:-MdXm6ia3pf58BfJhtLQ:b-205u1u) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter_test.cc#L335)):*
> ```cpp
> }
> 
> TEST(AnyInFilterTest, TestString) {
> ```

Could add a test for empty string.
Could add a test that the string value contains quote(").
___
*[src/main/cc/wfa/virtual_people/common/field_filter/in_filter_test.cc, line 280 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXtW59BNK40SO0iJ4i:-MdXtW59BNK40SO0iJ4j:b-l14gk6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/in_filter_test.cc#L280)):*
> ```cpp
> }
> 
> TEST(InFilterTest, TestEnumNumber) {
> ```

Could add a test for mix of enum value/number.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/in_filter_test.cc, line 318 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXoYt_-Q1KlHW6WE52:-MdXoYt_-Q1KlHW6WE53:b-xps7um) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/in_filter_test.cc#L318)):*
> ```cpp
> }
> 
> TEST(InFilterTest, TestString) {
> ```

Could add a test for empty string.
Could add a test for string value containing quote(").
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 188 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXozZi-nhZog2_7ztd:-MdXozZi-nhZog2_7zte:b2ldumf) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L188)):*
> ```objc
> // @message.
> //
> // @index must be in the boundary of the repeated field.
> ```

May want to point out that @index is a param in the GetImmediateValueFromRepeatedProto() method below. 
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 220 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXpqYy6e9egRiIMfjT:-MdXpqYy6e9egRiIMfjU:bbnvat) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L220)):*
> ```objc
> //
> // The typical usage is to first call GetFieldFromProto(see above), to get
> // @field_descriptors for the target field in @message, then call this function
> ```

Could add a step to get the size of the repeated field.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/type_convert_util.h, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXrjdHC3hVHcpMtQcK:-MdXrjdHC3hVHcpMtQcL:bhozl3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/utils/type_convert_util.h#L38)):*
> ```objc
> absl::StatusOr<ValueType> ConvertToNumeric(absl::string_view input);
> 
> // Convert the string @input to a enum value descriptor.
> ```

-> to an enum ...
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/values_parser_test.cc, line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXu4NU5LQPQGb3Bcmr:-MdXu4NU5LQPQGb3Bcms:b-hzfzq6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/utils/values_parser_test.cc#L94)):*
> ```cpp
> }
> 
> TEST(ValuesParserTest, TestString) {
> ```

Add a test for empty string.
Add a test for string value containing quote(").
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/values_parser_test.cc, line 111 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXtvNI5Tu2EH4W8JaU:-MdXtvNI5Tu2EH4W8JaV:b-fl1ek) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/utils/values_parser_test.cc#L111)):*
> ```cpp
>       ParseEnumValues(TestProtoB::TestEnum_descriptor(),
>                       "TEST_ENUM_1,TEST_ENUM_2,TEST_ENUM_1"));
>   EXPECT_THAT(parser_2.values, UnorderedElementsAre(1, 2));
> ```

Add a test for mix of value/number.

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16)* status: 18 of 23 files reviewed, 9 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter_test.cc, line 293 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXtcU97UHHbWeKe40I:-Md_eXMk9nAeYeSQItJP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter_test.cc#L293)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add a test for mix of enum value/number.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter_test.cc, line 335 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXm6ia3pf58BfJhtLP:-Md_eZ9q4jQMoboiOUOb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter_test.cc#L335)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add a test for empty string.
Could add a test that the string value contains quote(").
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/in_filter_test.cc, line 280 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXtW59BNK40SO0iJ4i:-Md_eZx19vskiMys_Q9q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/in_filter_test.cc#L280)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add a test for mix of enum value/number.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/in_filter_test.cc, line 318 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXoYt_-Q1KlHW6WE52:-Md_eaAU6L4AtM9gQkIK:b152rqm) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/in_filter_test.cc#L318)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add a test for empty string.
Could add a test for string value containing quote(").
</blockquote></details>

Added a test for string value with quote(").

Added a TODO to handle unset fields.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 188 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXozZi-nhZog2_7ztd:-Md_eoMIAYT4rnibLE1D:b-s41pcm) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L188)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

May want to point out that @index is a param in the GetImmediateValueFromRepeatedProto() method below. 
</blockquote></details>

Removed. This is unrelated to this function.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 220 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXpqYy6e9egRiIMfjT:-Md_fCOn0_uPHxW4gIt8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L220)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Could add a step to get the size of the repeated field.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/type_convert_util.h, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXrjdHC3hVHcpMtQcK:-Md_fD401Pi7UTE5gRr4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/utils/type_convert_util.h#L38)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

-> to an enum ...
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/values_parser_test.cc, line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXu4NU5LQPQGb3Bcmr:-Md_fDeCDYSYpURzfhr3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/utils/values_parser_test.cc#L94)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Add a test for empty string.
Add a test for string value containing quote(").
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/values_parser_test.cc, line 111 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdXtvNI5Tu2EH4W8JaU:-Md_fEU51rOZt4ga7GjO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f968d25dceae89375e9e08041ad60f3946ae40c1/src/main/cc/wfa/virtual_people/common/field_filter/utils/values_parser_test.cc#L111)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Add a test for mix of value/number.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16)* status: all files reviewed, 10 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 242 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdbUlKM0x3ZNl-cFY5X:-MdbUlKN1mWQUHQnR958:bl30uvh) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/688df5a5b69e94d228cd0f27c126ca19f609be37/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L242)):*
> ```objc
> //     std::vector<const google::protobuf::FieldDescriptor*> field_descriptors,
> //     GetFieldFromProto(
> //         MsgA().GetDescriptor(), "b.c", /*allow_repeated = */true));
> ```

supernit: `/*allow_repeated=*/` (without any internal spaces)

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16)* status: 22 of 23 files reviewed, 10 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 242 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16#-MdbUlKM0x3ZNl-cFY5X:-MdbzU5d1G7KwucOQawO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/688df5a5b69e94d228cd0f27c126ca19f609be37/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L242)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

supernit: `/*allow_repeated=*/` (without any internal spaces)
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16)* status: all files reviewed, 9 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

**Review by wliue — APPROVED** [review]
> Reviewed 13 of 23 files at r1, 5 of 6 files at r2, 4 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16)* status: all files reviewed, 9 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

**Pull request merged**
