### PR TITLE
Implement all hellper mehtods in FieldUtil.

### PR DESCRIPTION
**Pull request by wangyaopw**
Since kotlin proto Message is immutable, the methods use MessageOrBuilder for reader and Builder for write.

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/39)

### CODE REVIEW

**Review by wliue — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/39)* status: all files reviewed, 3 unresolved discussions (waiting on @tcsnfkx and @wangyaopw)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/39#-NAkzFmF6jXpe6tK1uKj):*
Nit: fix typo in description when merge.
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt` line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/39#-NAkzURjCT59q-C3I-3d:-NAkzURjCT59q-C3I-3e:bmtylum) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/4a623f13d69aa2b5a1caf68c5251e8bc029c973c/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt#L1)):*
> ```Kotlin
> // Copyright 2020 The Cross-Media Measurement Authors
> ```

Nit: What is the convention for the year here?
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt` line 34 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/39#-NAl-GY36p8GUJZKDE16:-NAl-GY36p8GUJZKDE17:b5d4489) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/4a623f13d69aa2b5a1caf68c5251e8bc029c973c/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt#L34)):*
> ```Kotlin
>  * path of which is represented by [fullFieldName].
>  *
>  * @param descriptor descriptor of the proto
> ```

Nit: end with '.'.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/39)* status: all files reviewed, 2 unresolved discussions (waiting on @tcsnfkx, @wangyaopw, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt` line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/39#-NAkzURjCT59q-C3I-3d:-NAlCCeu8zl_vc-uSVl0:blb0ekv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/4a623f13d69aa2b5a1caf68c5251e8bc029c973c/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt#L1)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Nit: What is the convention for the year here?
</blockquote></details>

Should be the current year.
Updated. Thanks!
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt` line 34 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/39#-NAl-GY36p8GUJZKDE16:-NAlCU7P4-Pk1HXikqJ4:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/4a623f13d69aa2b5a1caf68c5251e8bc029c973c/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt#L34)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Nit: end with '.'.
</blockquote></details>

done

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 7 of 9 files at r1, 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/39)* status: all files reviewed, 1 unresolved discussion (waiting on @tcsnfkx and @wangyaopw)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/39)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tcsnfkx)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/39#-NAkzFmF6jXpe6tK1uKj):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Nit: fix typo in description when merge.
</blockquote></details>

done

**Pull request merged**
