### PR TITLE
Read/write/compare uint32 and uint64 proto fields as unsigned values.

### PR DESCRIPTION
**Pull request by wangyaopw**
The proto field is read as Int and Long, we need to manually convert them to UInt and ULong before comparison.

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54)

### CODE REVIEW

**Comment by wangyaopw** [comment]
cc @JuliethHernandez

**Review by wliue — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt` line 115 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54#-NC14oII7ocXViOvO6A8:-NC14oII7ocXViOvO6A9:b-hmlpof) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7187e1c3460d6d9fb6c14ac9358801fda573b3c2/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt#L115)):*
> ```Kotlin
>     assertEquals(comparator.compare(testProto3), IntegerCompareResult.LESS_THAN)
> 
>     val testProto4 = testProto {
> ```

Nit: Could also add a case for -1.
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt` line 139 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54#-NC14pCx7C6N5dIRp3W0:-NC14pCx7C6N5dIRp3W1:b-hmlpof) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7187e1c3460d6d9fb6c14ac9358801fda573b3c2/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt#L139)):*
> ```Kotlin
>     assertEquals(comparator.compare(testProto3), IntegerCompareResult.LESS_THAN)
> 
>     val testProto4 = testProto {
> ```

Nit: Could also add a case for -1.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wliue)

___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt` line 115 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54#-NC14oII7ocXViOvO6A8:-NC15hp16nPoaoQhiqPA:bxc0j2o) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7187e1c3460d6d9fb6c14ac9358801fda573b3c2/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt#L115)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Nit: Could also add a case for -1.
</blockquote></details>

We can not set -1 to a uint32 field. The bits of -1 are the same as UInt.MAX_VALUE

`(-1).toUInt() == UInt.MAX_VALUE == 4294967295 `



_Code quote:_
```Kotlin
uint32Value 
```
___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt` line 139 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54#-NC14pCx7C6N5dIRp3W0:-NC16HYkCpo5010gB9zS:bb7od0r) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7187e1c3460d6d9fb6c14ac9358801fda573b3c2/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt#L139)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Nit: Could also add a case for -1.
</blockquote></details>

same

**Review by wliue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54)* status: 9 of 13 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @wliue)

___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt` line 115 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54#-NC14oII7ocXViOvO6A8:-NC1FqjsBVb7i6HebBqK:b-qmzpfv) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7187e1c3460d6d9fb6c14ac9358801fda573b3c2/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt#L115)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

We can not set -1 to a uint32 field. The bits of -1 are the same as UInt.MAX_VALUE

`(-1).toUInt() == UInt.MAX_VALUE == 4294967295 `
</blockquote></details>

But the result of toInt() is -1, so this sets -1 to a uint32 field, correct?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54)* status: 8 of 13 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wliue)

___
*[`src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt` line 115 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54#-NC14oII7ocXViOvO6A8:-NC1Gvdj9Xn2VwbbleQh:b-o0ciyy) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7187e1c3460d6d9fb6c14ac9358801fda573b3c2/src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt#L115)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

But the result of toInt() is -1, so this sets -1 to a uint32 field, correct? 
</blockquote></details>

oh, yes, you are right.

added another case so it is more obvious

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 5 files at r3, 3 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt` line 146 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54#-NC1Bsk2E9VTkW8kFZWo:-NC1Bsk2E9VTkW8kFZWp:b-5p1kol) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/333168feed2070770ddf67d9f7c23476817b5abe/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt#L146)):*
> ```Kotlin
>   return when (val result = message.getField(fieldDescriptor)) {
>     is V -> result
>     is Int -> result.toUInt() as V
> ```

I'm a little bit worried about this being brittle. It's relying on the assumption that the only thing an Int could be if it's not a `V` is a `UInt`. Since V is reified here, we double-check what `V` is to make sure we don't end up with a casting error.

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 3 files at r2, 5 of 5 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @wliue)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt` line 146 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54#-NC1Bsk2E9VTkW8kFZWo:-NC1rsaE4PkmrVNvg0Vc:b-y9gfo3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/333168feed2070770ddf67d9f7c23476817b5abe/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt#L146)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm a little bit worried about this being brittle. It's relying on the assumption that the only thing an Int could be if it's not a `V` is a `UInt`. Since V is reified here, we double-check what `V` is to make sure we don't end up with a casting error.
</blockquote></details>

I retied that, but the code doesn't compile.

```
  val result = message.getField(fieldDescriptor)
  return if (result is V) {
    return result
  } else if (result is Int) {
    result.toUInt() as V
  } else if (result is Long && 1UL is V) {
    result.toULong() as V
  } else {
    error("The type of the field is not compatible to the target")
  }
```

The error is 
"
This function has a reified type parameter and thus can only be inlined at compilation time, not called directly.
"

I couldn't find a way to check if V is UInt or ULong

Any suggestions?

I am less worried about a casting error, if the type is not compatible, it will be an error, either thrown by us explicit or by a casting error

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt` line 146 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54#-NC1Bsk2E9VTkW8kFZWo:-NC1vgBh0SDEuUdVLGmx:bpsvcso) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/333168feed2070770ddf67d9f7c23476817b5abe/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt#L146)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I retied that, but the code doesn't compile.

```
  val result = message.getField(fieldDescriptor)
  return if (result is V) {
    return result
  } else if (result is Int) {
    result.toUInt() as V
  } else if (result is Long && 1UL is V) {
    result.toULong() as V
  } else {
    error("The type of the field is not compatible to the target")
  }
```

The error is 
"
This function has a reified type parameter and thus can only be inlined at compilation time, not called directly.
"

I couldn't find a way to check if V is UInt or ULong

Any suggestions?

I am less worried about a casting error, if the type is not compatible, it will be an error, either thrown by us explicit or by a casting error
</blockquote></details>

```
  val result = message.getField(fieldDescriptor)
  return if (result is V) {
    return result
  } else if (result is Int && 1U is V) {
    result.toUInt() as V
  } else if (result is Long && 1UL is V) {
    result.toULong() as V
  } else {
    error("The type of the field is not compatible to the target")
  }
```

**Review by wliue — APPROVED** [review]
> Reviewed 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @wangyaopw and @wliue)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54#-NC2FK1m0ZjzUbhR3BTs:-NC2FK1n-fu9jFYq6AyH:b-ah5jv1) (no related file):*
Are any of these functions supposed to be callable from Java? ULong and UInt are Kotlin-specific types.

___
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt` line 146 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54#-NC1Bsk2E9VTkW8kFZWo:-NC2EoS45UaqL2nLxRq0:bid4ito) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/333168feed2070770ddf67d9f7c23476817b5abe/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt#L146)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

```
  val result = message.getField(fieldDescriptor)
  return if (result is V) {
    return result
  } else if (result is Int && 1U is V) {
    result.toUInt() as V
  } else if (result is Long && 1UL is V) {
    result.toULong() as V
  } else {
    error("The type of the field is not compatible to the target")
  }
```
</blockquote></details>

I don't think you can do `is V`. You'd have to check against `V::class`.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @wliue)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54#-NC2FK1m0ZjzUbhR3BTs:-NC2FrMw81HN5AbLCGvA:b-a8m45q) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Are any of these functions supposed to be callable from Java? ULong and UInt are Kotlin-specific types.
</blockquote></details>

No. In Java, we only call `Labeler.build()` and `labeler.apply()` Nothing else. 

___
___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt` line 146 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54#-NC1Bsk2E9VTkW8kFZWo:-NC2HPp2ElFOWS9lv89O:b-xfo0nq) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/333168feed2070770ddf67d9f7c23476817b5abe/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt#L146)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think you can do `is V`. You'd have to check against `V::class`.
</blockquote></details>

I tried that too. I couldn't event make the code compile using V::class here.

Do you mind have a try when you get some spare time?

You can just run `bazel test src/test/kotlin/...` to find the error I mentioned.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54)* status: 9 of 13 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt` line 146 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54#-NC1Bsk2E9VTkW8kFZWo:-NC6VZlx2COY6rI7pS--:b-ziae4z) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/333168feed2070770ddf67d9f7c23476817b5abe/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt#L146)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I tried that too. I couldn't event make the code compile using V::class here.

Do you mind have a try when you get some spare time?

You can just run `bazel test src/test/kotlin/...` to find the error I mentioned.
</blockquote></details>

`V::class == UInt::class` works

See https://pl.kotl.in/ibGeBGFgW

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54)* status: 9 of 13 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @wliue)

___
*[`src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt` line 146 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54#-NC1Bsk2E9VTkW8kFZWo:-NC6_f1bBzJ09CxBfYoh:bnbbdey) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/333168feed2070770ddf67d9f7c23476817b5abe/src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt#L146)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`V::class == UInt::class` works

See https://pl.kotl.in/ibGeBGFgW
</blockquote></details>

oh, awesome. I didn't try this way

Thanks. Updated.

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wliue)

**Pull request merged**
