### PR TITLE
Implement FieldFilterProto with op as GT and LT.

### PR DESCRIPTION
**Pull request by tcsnfkx**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/gt_filter.h, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13#-MbgReWZ1HwtE1D8CBkX:-MbgReWZ1HwtE1D8CBkY:b-ei2tzu) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ea4c489adf2a14847b150557564e31ca43aff96e/src/main/cc/wfa/virtual_people/common/field_filter/gt_filter.h#L57)):*
> ```objc
> 
>  private:
>   std::unique_ptr<IntegerComparator> comparator_;
> ```

I have a general design question. We have lots and lots of indirects in the implementation of all the field filters. This will come with a fairly hefty performance cost: to compare an integer, instead of just executing a `cmp` then `je` instruction, it first has to go follow pointers, do vtable lookups, etc.

Is it worth reconsidering some of this?

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/gt_filter.h, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13#-MbgReWZ1HwtE1D8CBkX:-Mblztzj2ThJ8rPoAPUS:b-6gp9xf) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ea4c489adf2a14847b150557564e31ca43aff96e/src/main/cc/wfa/virtual_people/common/field_filter/gt_filter.h#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I have a general design question. We have lots and lots of indirects in the implementation of all the field filters. This will come with a fairly hefty performance cost: to compare an integer, instead of just executing a `cmp` then `je` instruction, it first has to go follow pointers, do vtable lookups, etc.

Is it worth reconsidering some of this?
</blockquote></details>

As discussed offline, we do not think this is the major impact on the performance. We will continue with the current implementation. We can revisit this if there is any perf issue in future.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

**Review by wliue — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13)* status: all files reviewed, 5 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13#-MbnJs81BRUzBkTmgqDu:-MbnJs81BRUzBkTmgqDv:bf8tqts) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ea4c489adf2a14847b150557564e31ca43aff96e/src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h#L68)):*
> ```objc
> // A a_2;
> // a_2.mutable_b()->set_c(10);
> // IntegerCompareResult result_1 = comparator.Compare(a_2);  // EQUAL
> ```

-> result_2 to be consistent
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13#-MbnJvrY6yhXYi_LTLCW:-MbnJvrY6yhXYi_LTLCX:b-18sz4h) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ea4c489adf2a14847b150557564e31ca43aff96e/src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h#L72)):*
> ```objc
> // A a_3;
> // a_3.mutable_b()->set_c(9);
> // IntegerCompareResult result_1 = comparator.Compare(a_3);  // LESS_THAN
> ```

-> result_3 to be consistent
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h, line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13#-MbnK9BC1CpNgSVxk6Fd:-MbnK9BC1CpNgSVxk6Fe:b-zgstty) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ea4c489adf2a14847b150557564e31ca43aff96e/src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h#L78)):*
> ```objc
>   //
>   // Returns error status if any of the following happens:
>   // * The last entry of @field_descriptors refers to a non-integer field.
> ```

Is repeated field allowed, in the path or the target field?
Could add comment that this would be caught earlier if following the usage example.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h, line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13#-MbnLT6sBXIXW61KOimN:-MbnLT6sBXIXW61KOimO:bw387ga) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ea4c489adf2a14847b150557564e31ca43aff96e/src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h#L104)):*
> ```objc
>   ): field_descriptors_(std::move(field_descriptors)) {}
> 
>   std::vector<const google::protobuf::FieldDescriptor*> field_descriptors_;
> ```

Add private: ?
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator_test.cc, line 63 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13#-MbnMGU59pkztap3W5OW:-MbnMGU59pkztap3W5OX:bnc8n0f) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ea4c489adf2a14847b150557564e31ca43aff96e/src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator_test.cc#L63)):*
> ```cpp
> 
> TEST(IntegerComparatorTest, FloatValue) {
>   // "-1" is not a valid uint32.
> ```

Update this comment.

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13)* status: 10 of 12 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13#-MbnJs81BRUzBkTmgqDu:-MboSIMx3ltna84Grw71:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ea4c489adf2a14847b150557564e31ca43aff96e/src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h#L68)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

-> result_2 to be consistent
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13#-MbnJvrY6yhXYi_LTLCW:-MboSHoMD_wXrBm8DLK7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ea4c489adf2a14847b150557564e31ca43aff96e/src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h#L72)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

-> result_3 to be consistent
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h, line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13#-MbnK9BC1CpNgSVxk6Fd:-MboSJ8HA3neCu3XNw4_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ea4c489adf2a14847b150557564e31ca43aff96e/src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h#L78)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Is repeated field allowed, in the path or the target field?
Could add comment that this would be caught earlier if following the usage example.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h, line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13#-MbnLT6sBXIXW61KOimN:-MboRd5q8msRZ2Xs85Je:b-tesep3) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ea4c489adf2a14847b150557564e31ca43aff96e/src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h#L104)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Add private: ?
</blockquote></details>

This field is used by all the child classes, and required to be "protected".
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator_test.cc, line 63 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13#-MbnMGU59pkztap3W5OW:-MboSKt9AlNg4JPZwpXI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/ea4c489adf2a14847b150557564e31ca43aff96e/src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator_test.cc#L63)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Update this comment.
</blockquote></details>

Done.

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13)* status: 10 of 12 files reviewed, all discussions resolved (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, and @oliver-amzn)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, and @oliver-amzn)

**Review by mpatel24 — APPROVED** [review]

**Pull request merged**
