### PR TITLE
Update the file paths and namespaces to follow the convention of Cross Media Measurement repos.

### PR DESCRIPTION
**Pull request by tcsnfkx**
Move all protobuf files from src/proto to src/main/proto/wfa/virtual_people/common.

Change namespaces from virtual_people to wfa.virtual_people.common.

### CODE REVIEW

**Review by lenjoy — APPROVED** [review]

**Review by wliue — APPROVED** [review]

**Review by SanjayVas — CHANGES_REQUESTED** [review]
Not important for this PR, but note that we eventually want to restructure our C++ namespaces to reduce nesting as per https://abseil.io/tips/130. Protocol buffer packages map 1:1 with C++ namespaces. We have a Google-internal doc discussing this that I can share with the WFA workstreams.

CC @wangyaopw

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/3#-:-MXs6jvs2eCKTb9_ytcG:bne6bjw)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[src/main/proto/wfa/virtual_people/common/event.proto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/3#-MXs83vN8kF-6wMMQ5H9:-MXs83vOE0vMjiWZU6UZ:bmavf1e) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/9d21c2c2131a7dbafa816183bbb381e0bb7a90d0/src/main/proto/wfa/virtual_people/common/event.proto#L17)):*
> ```
> common
> ```
I don't think we need a nested `common` namespace for shared protocol buffers.

Note that this advice only applies to C++ namespaces. Our practice for JVM packages would still put this in a `common` subpackage using the `java_package` proto option if this were to be used from a JVM language. It's also fine for them to remain in a `common` subdirectory, as C++ namespaces need not match the directory structure.

**Review by SanjayVas — COMMENTED** [review]
> Moves all protobuf files from src/proto to
> src/main/proto/wfa/virtual_people/common.
Commit message subject (first line) should be an imperative statement, e.g. "Move all ..." rather than "Moves all ..."

Note that for single-commit PRs, the merged PR message will be copied from the commit message.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/3#-:-MXs9XwM58AR4sTsdAuD:b-b1iq9g)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @my2457, @oliver-amzn, and @tcsnfkx)

**Comment by tcsnfkx** [comment]
> Not important for this PR, but note that we eventually want to restructure our C++ namespaces to reduce nesting as per https://abseil.io/tips/130. Protocol buffer packages map 1:1 with C++ namespaces. We have a Google-internal doc discussing this that I can share with the WFA workstreams.
> 
> CC @wangyaopw
> 
> > Reviewed 4 of 4 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/3#-:-MXs6jvs2eCKTb9_ytcG:bne6bjw)_ status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @my2457, @oliver-amzn, and @tcsnfkx)
> 
> _[src/main/proto/wfa/virtual_people/common/event.proto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/3#-MXs83vN8kF-6wMMQ5H9:-MXs83vOE0vMjiWZU6UZ:bmavf1e) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/9d21c2c2131a7dbafa816183bbb381e0bb7a90d0/src/main/proto/wfa/virtual_people/common/event.proto#L17)):_
> 
> > ```
> > common
> > ```
> 
> I don't think we need a nested `common` namespace for shared protocol buffers.
> 
> Note that this advice only applies to C++ namespaces. Our practice for JVM packages would still put this in a `common` subpackage using the `java_package` proto option if this were to be used from a JVM language. It's also fine for them to remain in a `common` subdirectory, as C++ namespaces need not match the directory structure.



> Not important for this PR, but note that we eventually want to restructure our C++ namespaces to reduce nesting as per https://abseil.io/tips/130. Protocol buffer packages map 1:1 with C++ namespaces. We have a Google-internal doc discussing this that I can share with the WFA workstreams.
> 
> CC @wangyaopw
> 
> > Reviewed 4 of 4 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/3#-:-MXs6jvs2eCKTb9_ytcG:bne6bjw)_ status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @my2457, @oliver-amzn, and @tcsnfkx)
> 
> _[src/main/proto/wfa/virtual_people/common/event.proto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/3#-MXs83vN8kF-6wMMQ5H9:-MXs83vOE0vMjiWZU6UZ:bmavf1e) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/9d21c2c2131a7dbafa816183bbb381e0bb7a90d0/src/main/proto/wfa/virtual_people/common/event.proto#L17)):_
> 
> > ```
> > common
> > ```
> 
> I don't think we need a nested `common` namespace for shared protocol buffers.
> 
> Note that this advice only applies to C++ namespaces. Our practice for JVM packages would still put this in a `common` subpackage using the `java_package` proto option if this were to be used from a JVM language. It's also fine for them to remain in a `common` subdirectory, as C++ namespaces need not match the directory structure.

".common" removed.

**Comment by tcsnfkx** [comment]
> > Moves all protobuf files from src/proto to
> > src/main/proto/wfa/virtual_people/common.
> > Commit message subject (first line) should be an imperative statement, e.g. "Move all ..." rather than "Moves all ..."
> 
> Note that for single-commit PRs, the merged PR message will be copied from the commit message.
> 
> > _[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/3#-:-MXs9XwM58AR4sTsdAuD:b-b1iq9g)_ status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @my2457, @oliver-amzn, and @tcsnfkx)

PR message modified.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/3)* status: all files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @my2457, @oliver-amzn, and @tcsnfkx)

**Pull request merged**
