### PR TITLE
Creates the AUTHORS file.

### PR DESCRIPTION
**Pull request by tcsnfkx**

### CODE REVIEW

**Comment by jeremydstone** [comment]
Congrats on first PR!

**Comment by tcsnfkx** [comment]
> Congrats on first PR!

**Comment by tcsnfkx** [comment]
> Congrats on first PR!

Thank you!

**Review by wliue — APPROVED** [review]

**Review by EvgSkv — APPROVED** [review]

**Review by oliver-amzn — APPROVED** [review]
👍

**Review by lenjoy — APPROVED** [review]
LGTM

**Pull request merged**
