### PR TITLE
Add notes to all fingerprint fields in our protos.

### PR DESCRIPTION
**Pull request by wangyaopw**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones, @tcsnfkx, @wangyaopw, and @wliue)

___
*[`src/main/proto/wfa/virtual_people/common/event.proto` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53#-NByTn71C6nTD2uoIiO6:-NByTn71C6nTD2uoIiO7:b-itvuqi) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7b95b29345f468949122045b04129553a78c5ead/src/main/proto/wfa/virtual_people/common/event.proto#L40)):*
I'm not sure this is the best place for this. It's a general thing about how protobuf Java works, as documented in https://developers.google.com/protocol-buffers/docs/proto#scalar:

> In Java, unsigned 32-bit and 64-bit integers are represented using their signed counterparts, with the top bit simply being stored in the sign bit.

Additionally, `ULong` is Kotlin-specific. Finally, whether you even need to cast to that entirely depends on what you're doing with the underlying bits. It's entirely possible to use `long` and still get the right result as long as your library code understands how the bits are encoded.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, @tcsnfkx, and @wliue)

___
*[`src/main/proto/wfa/virtual_people/common/event.proto` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53#-NByTn71C6nTD2uoIiO6:-NByfQTa0QBxxVe97jpp:beym9ya) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7b95b29345f468949122045b04129553a78c5ead/src/main/proto/wfa/virtual_people/common/event.proto#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not sure this is the best place for this. It's a general thing about how protobuf Java works, as documented in https://developers.google.com/protocol-buffers/docs/proto#scalar:

> In Java, unsigned 32-bit and 64-bit integers are represented using their signed counterparts, with the top bit simply being stored in the sign bit.

Additionally, `ULong` is Kotlin-specific. Finally, whether you even need to cast to that entirely depends on what you're doing with the underlying bits. It's entirely possible to use `long` and still get the right result as long as your library code understands how the bits are encoded.
</blockquote></details>

Sometimes we use the fingerprint as part of the seed of hashing. For example

```
uint64_t seed = util::Fingerprint64(
        absl::StrCat(random_seed_, event.acting_fingerprint()));
```

https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4d945b142ea2204543e4c332bea892c80e610898/src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc#L119

the acting_fingerprint field in proto is uint64, but kotlin reads it as Long

The equivalent kotlin code for the parameter would be 
```
"$randomSeed${event.actingFingerprint.toULong}"
```
If we forget the casting, the kotlin behavior will be different from the C++.

For all the other places that actually use the numeric value, the code knows how to handle the Long type appropriately. But if it uses the string value of it, we need to make sure we cast it to ULong.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones, @tcsnfkx, @wangyaopw, and @wliue)

___
*[`src/main/proto/wfa/virtual_people/common/event.proto` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53#-NByTn71C6nTD2uoIiO6:-NBypDl9CImbrKrn08gB:b-964w51) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7b95b29345f468949122045b04129553a78c5ead/src/main/proto/wfa/virtual_people/common/event.proto#L40)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Sometimes we use the fingerprint as part of the seed of hashing. For example

```
uint64_t seed = util::Fingerprint64(
        absl::StrCat(random_seed_, event.acting_fingerprint()));
```

https://github.com/world-federation-of-advertisers/virtual-people-core-serving/blob/4d945b142ea2204543e4c332bea892c80e610898/src/main/cc/wfa/virtual_people/core/model/population_node_impl.cc#L119

the acting_fingerprint field in proto is uint64, but kotlin reads it as Long

The equivalent kotlin code for the parameter would be 
```
"$randomSeed${event.actingFingerprint.toULong}"
```
If we forget the casting, the kotlin behavior will be different from the C++.

For all the other places that actually use the numeric value, the code knows how to handle the Long type appropriately. But if it uses the string value of it, we need to make sure we cast it to ULong.
</blockquote></details>

What I'm getting at is this is specific to the implementation. Your string parameter is defined as "the concatenation of a random seed in [X format] and the string representation of id_fingerprint as an unsigned 64-bit integer".

There are multiple ways to accomplish this. `toUlong()` just happens to be the simplest in Kotlin. Another would be `Long.toUnsignedString`. Regardless, the protobuf isn't the right place to document this nor is the correct documentation to say "cast to ULong".

The documentation should be on whatever needs it to be in that string format above. The fact that Java/Kotlin use the `long` data type for this field is just a factor of the official Java protobuf generated code. Note that one could use an alternate protoc plugin or some other hand-written implementation of Java protobuf as long as it follows the protobuf wire format spec.

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, @tcsnfkx, and @wliue)

___
*[`src/main/proto/wfa/virtual_people/common/event.proto` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53#-NByTn71C6nTD2uoIiO6:-NByziaZ7ROPCNc_aaVL:bisercn) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7b95b29345f468949122045b04129553a78c5ead/src/main/proto/wfa/virtual_people/common/event.proto#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What I'm getting at is this is specific to the implementation. Your string parameter is defined as "the concatenation of a random seed in [X format] and the string representation of id_fingerprint as an unsigned 64-bit integer".

There are multiple ways to accomplish this. `toUlong()` just happens to be the simplest in Kotlin. Another would be `Long.toUnsignedString`. Regardless, the protobuf isn't the right place to document this nor is the correct documentation to say "cast to ULong".

The documentation should be on whatever needs it to be in that string format above. The fact that Java/Kotlin use the `long` data type for this field is just a factor of the official Java protobuf generated code. Note that one could use an alternate protoc plugin or some other hand-written implementation of Java protobuf as long as it follows the protobuf wire format spec.
</blockquote></details>

What you said makes perfect sense. I updated the comment a little bit, WDYT?

Just want to warn whoever touches the code about this in the future, since this is the most likely place that would result in behave difference between the C++ and kotlin labeler.

I'll add comment to the kotlin code too, which is in another repo.

**Review by wliue — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @tcsnfkx)

___
*[`src/main/proto/wfa/virtual_people/common/event.proto` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53#-NByTn71C6nTD2uoIiO6:-NC1-zwA9G2eqo8BXuB3:bdek7to) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7b95b29345f468949122045b04129553a78c5ead/src/main/proto/wfa/virtual_people/common/event.proto#L40)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

What you said makes perfect sense. I updated the comment a little bit, WDYT?

Just want to warn whoever touches the code about this in the future, since this is the most likely place that would result in behave difference between the C++ and kotlin labeler.

I'll add comment to the kotlin code too, which is in another repo.
</blockquote></details>

Do we need similar comments for all uint32 and uint64 fields? For example, node index and population pool offset/size.
Also, we plan to change virtual person id from int64 to uint64. Would that cause any issue?

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @tcsnfkx)

___
*[`src/main/proto/wfa/virtual_people/common/event.proto` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53#-NByTn71C6nTD2uoIiO6:-NC16lYsBBdHUAng7VpE:b-4js7hq) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7b95b29345f468949122045b04129553a78c5ead/src/main/proto/wfa/virtual_people/common/event.proto#L40)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Do we need similar comments for all uint32 and uint64 fields? For example, node index and population pool offset/size.
Also, we plan to change virtual person id from int64 to uint64. Would that cause any issue?
</blockquote></details>

node index and population pool offset/size are unlikely to exceed int32.MAX_VALUE and int64.MAX_VALUE. But fingerprints have 50% chance exceeding the limits. So I think no need to worry about those two.

If the population pool offset+size is less than int64.MAX_VALUE (18446744073709551615), then changing virtual person id from int64 to uint64 should be fine. Otherwise, we might need to make some change. 

If all tests still pass, we should be good.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @tcsnfkx)

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @tcsnfkx)

___
*[`src/main/proto/wfa/virtual_people/common/event.proto` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53#-NByTn71C6nTD2uoIiO6:-NC18-jKErirHjQYun7O:bju7m3x) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7b95b29345f468949122045b04129553a78c5ead/src/main/proto/wfa/virtual_people/common/event.proto#L40)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

node index and population pool offset/size are unlikely to exceed int32.MAX_VALUE and int64.MAX_VALUE. But fingerprints have 50% chance exceeding the limits. So I think no need to worry about those two.

If the population pool offset+size is less than int64.MAX_VALUE (18446744073709551615), then changing virtual person id from int64 to uint64 should be fine. Otherwise, we might need to make some change. 

If all tests still pass, we should be good.
</blockquote></details>

We definitely need to adjust the kotlin implementation a little bit when updating the data type of the virtual people id. Should be very simple update.

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @tcsnfkx)

**Comment by wliue** [comment]
*[`src/main/proto/wfa/virtual_people/common/event.proto` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53#-NByTn71C6nTD2uoIiO6:-NC1AU4e8AGqBAsn4kX2:beexuie) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/7b95b29345f468949122045b04129553a78c5ead/src/main/proto/wfa/virtual_people/common/event.proto#L40)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

We definitely need to adjust the kotlin implementation a little bit when updating the data type of the virtual people id. Should be very simple update.
</blockquote></details>

Node index is not necessarily consecutive, so in theory it can exceed int32.MAX_VALUE. In practice we expect this is mostly used by model compiler and wouldn't exceed.
 
The population pools offset can be larger than int64.MAX_VALUE, because it is arbitrary in the sense that MP may choose specific range for various purpose. That is actually the reason why we plan to update vpid type to match.

**Comment by wangyaopw** [comment]
So let's just do it. If you update the proto in the common-repo, I can update both the c++ and kotlin labeler implementation.

**Comment by wangyaopw** [comment]
we don't need to worry about node index since it is just used as the key in the nodeRef map. Reading uint32 as int32 doesn't matter.

**Pull request merged**
