### PR TITLE
Support more field filters and handle repeated fields

### PR DESCRIPTION
**Pull request by tcsnfkx**
Implement FieldFilterProto with op as OR.
Implement FieldFilterProto with op as NOT.
Implement FieldFilterProto with op as HAS.
Handles repeated fields in field filters.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12)* status: all files reviewed, 6 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/has_filter.h, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbIEuYO1ClHVFQlLDUQ:-MbIEuYO1ClHVFQlLDUR:bs9p2p6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/c6a0dedb18179c4c890ce237de88518c16244212/src/main/cc/wfa/virtual_people/common/field_filter/has_filter.h#L38)):*
> ```objc
>   //   is repeated field.
>   static absl::StatusOr<std::unique_ptr<HasFilter>> New(
>       const google::protobuf::Descriptor* descriptor,
> ```

Nullable? If not, please use const reference
___
*[src/main/cc/wfa/virtual_people/common/field_filter/has_filter.cc, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbIF8ow8wm3Ckzcrtiv:-MbIF8ow8wm3Ckzcrtiw:bwhecvh) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/c6a0dedb18179c4c890ce237de88518c16244212/src/main/cc/wfa/virtual_people/common/field_filter/has_filter.cc#L52)):*
> ```cpp
>   const google::protobuf::FieldDescriptor* field = field_descriptors_.back();
>   if (field->is_repeated()) {
>     return (parent.GetReflection()->FieldSize(parent, field) > 0);
> ```

Nit: unnecessary parens
___
*[src/main/cc/wfa/virtual_people/common/field_filter/not_filter.h, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbIFHf72nIpj8p7kUM5:-MbIFHf72nIpj8p7kUM6:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/c6a0dedb18179c4c890ce237de88518c16244212/src/main/cc/wfa/virtual_people/common/field_filter/not_filter.h#L37)):*
> ```objc
>   //    Any of @config.sub_filters is invalid to create a FieldFilter.
>   static absl::StatusOr<std::unique_ptr<NotFilter>> New(
>       const google::protobuf::Descriptor* descriptor,
> ```

Ditto
___
*[src/main/cc/wfa/virtual_people/common/field_filter/or_filter.h, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbIFWiE7o6GFpGxDJQp:-MbIFWiE7o6GFpGxDJQq:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/c6a0dedb18179c4c890ce237de88518c16244212/src/main/cc/wfa/virtual_people/common/field_filter/or_filter.h#L37)):*
> ```objc
>   //    Any of @config.sub_filters is invalid to create a FieldFilter.
>   static absl::StatusOr<std::unique_ptr<OrFilter>> New(
>       const google::protobuf::Descriptor* descriptor,
> ```

Ditto
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.cc, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbIFtdwAEwvQqUxFthS:-MbIFtdwAEwvQqUxFthT:b272eii) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/c6a0dedb18179c4c890ce237de88518c16244212/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.cc#L49)):*
> ```cpp
>   }
>   for (auto it = field_descriptors.begin(), j = field_descriptors.end() - 1;
>        it != j; it++) {
> ```

++it please
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.cc, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbIFvhL-peZhk8fQ9V7:-MbIFvhL-peZhk8fQ9V8:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/c6a0dedb18179c4c890ce237de88518c16244212/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.cc#L68)):*
> ```cpp
>   const google::protobuf::Message* tmp_message = &message;
>   for (auto it = field_descriptors.begin(), j = field_descriptors.end() - 1;
>        it != j; it++) {
> ```

Ditto

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12)* status: 18 of 20 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/has_filter.h, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbIEuYO1ClHVFQlLDUQ:-MbJX1Pm5skRaOAeSVAD:bom92rc) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/c6a0dedb18179c4c890ce237de88518c16244212/src/main/cc/wfa/virtual_people/common/field_filter/has_filter.h#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Nullable? If not, please use const reference
</blockquote></details>

Null descriptor is supported here, though the use case is very rare.
The default usage of protobuf descriptors is through the pointer.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/has_filter.cc, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbIF8ow8wm3Ckzcrtiv:-MbJYgN-0IwXJoyDNSQ3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/c6a0dedb18179c4c890ce237de88518c16244212/src/main/cc/wfa/virtual_people/common/field_filter/has_filter.cc#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Nit: unnecessary parens
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/not_filter.h, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbIFHf72nIpj8p7kUM5:-MbJXu9N510qtiDgXv-0:b2nreh6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/c6a0dedb18179c4c890ce237de88518c16244212/src/main/cc/wfa/virtual_people/common/field_filter/not_filter.h#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Same as above.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/or_filter.h, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbIFWiE7o6GFpGxDJQp:-MbJY2jw9xPGrWQJjTl6:b2nreh6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/c6a0dedb18179c4c890ce237de88518c16244212/src/main/cc/wfa/virtual_people/common/field_filter/or_filter.h#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Same as above.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.cc, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbIFtdwAEwvQqUxFthS:-MbJYkTNABmYJWs9jfka:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/c6a0dedb18179c4c890ce237de88518c16244212/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.cc#L49)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

++it please
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.cc, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbIFvhL-peZhk8fQ9V7:-MbJYl4TDGaoG6HTpJuo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/c6a0dedb18179c4c890ce237de88518c16244212/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.cc#L68)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @kunyuchen, @lenjoy, @mpatel24, @my2457, @oliver-amzn, and @wliue)

**Review by mpatel24 — APPROVED** [review]

**Review by wliue — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12)* status: all files reviewed, 4 unresolved discussions (waiting on @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @tcsnfkx)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/not_filter_test.cc, line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbOJQd00-eoaDtoGd-Q:-MbOJQd00-eoaDtoGd-R:b-awm90r) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f3919fe6f05a99d1769adbfcbfd54bf763ba9822/src/main/cc/wfa/virtual_people/common/field_filter/not_filter_test.cc#L72)):*
> ```
> TEST(NotFilterTest, TestMatch)
> ```

Could add a case for empty proto, and/or none of sub_filter passes.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/or_filter_test.cc, line 82 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbOJghDCeg-7UJ_swUG:-MbOJghDCeg-7UJ_swUH:b-cbyc7m) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f3919fe6f05a99d1769adbfcbfd54bf763ba9822/src/main/cc/wfa/virtual_people/common/field_filter/or_filter_test.cc#L82)):*
> ```
> TEST(OrFilterTest, TestNotMatch)
> ```

Could add a case for empty proto.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbOM3-pCZ2vK1tNWsPO:-MbOM3-q3-jQWxsHxmcu:b-hloflg) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f3919fe6f05a99d1769adbfcbfd54bf763ba9822/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L44)):*
> ```
> // Get the parent message of the field represented by @field_descriptors from
> // the @message.
> ```

Is it expected that the caller already checked that the parent field is set before calling this?
If so, add comment to that effect.
Otherwise add comment for error condition, and add a test case.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbOMwKX-Yy90uuIx8xM:-MbOMwKX-Yy90uuIx8xN:bkkkcyh) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f3919fe6f05a99d1769adbfcbfd54bf763ba9822/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L87)):*
> ```
> // Get the value from the @message, with field path represented by
> // @field_descriptors.
> ```

Is it expected that the caller already checked that the field is set before calling this?
If so, add comment to that effect.
Otherwise add comment for error condition, and add a test case.

**Review by tcsnfkx — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12)* status: 16 of 20 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/not_filter_test.cc, line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbOJQd00-eoaDtoGd-Q:-MbPU8lN1QaT_1ucXU3d:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f3919fe6f05a99d1769adbfcbfd54bf763ba9822/src/main/cc/wfa/virtual_people/common/field_filter/not_filter_test.cc#L72)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
> TEST(NotFilterTest, TestMatch)
> ```

Could add a case for empty proto, and/or none of sub_filter passes.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/or_filter_test.cc, line 82 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbOJghDCeg-7UJ_swUG:-MbPU9hA85wC9aDk_6Iq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f3919fe6f05a99d1769adbfcbfd54bf763ba9822/src/main/cc/wfa/virtual_people/common/field_filter/or_filter_test.cc#L82)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
> TEST(OrFilterTest, TestNotMatch)
> ```

Could add a case for empty proto.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbOM3-pCZ2vK1tNWsPO:-MbOcGS6-jdPO2TYVS1J:b-w26ptc) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f3919fe6f05a99d1769adbfcbfd54bf763ba9822/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L44)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
> // Get the parent message of the field represented by @field_descriptors from
> // the @message.
> ```

Is it expected that the caller already checked that the parent field is set before calling this?
If so, add comment to that effect.
Otherwise add comment for error condition, and add a test case.
</blockquote></details>

Test added. The parent message is not required to be set. Calling on the unset parent message returns the default empty message.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbOMwKX-Yy90uuIx8xM:-MbPSaYwBbyBTFN-4Udf:b-ao00y4) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f3919fe6f05a99d1769adbfcbfd54bf763ba9822/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L87)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

> ```
> // Get the value from the @message, with field path represented by
> // @field_descriptors.
> ```

Is it expected that the caller already checked that the field is set before calling this?
If so, add comment to that effect.
Otherwise add comment for error condition, and add a test case.
</blockquote></details>

Test added. The field is not required to be set. Calling with unset field returns default value.

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12)* status: 16 of 20 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @EvgSkv, @kunyuchen, @lenjoy, @my2457, @oliver-amzn, @tcsnfkx, and @wliue)

___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbOM3-pCZ2vK1tNWsPO:-MbPj_leC1AF7Ic6hO-a:buynna8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f3919fe6f05a99d1769adbfcbfd54bf763ba9822/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L44)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Test added. The parent message is not required to be set. Calling on the unset parent message returns the default empty message.
</blockquote></details>

This is ok for now because we documented the expected behavior. But we may want to revisit this later. In particular, for filters that check EQUAL to default value.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbOMwKX-Yy90uuIx8xM:-MbPkfp97kj93J0lIKth:buynna8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f3919fe6f05a99d1769adbfcbfd54bf763ba9822/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h#L87)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Test added. The field is not required to be set. Calling with unset field returns default value.
</blockquote></details>

This is ok for now because we documented the expected behavior. But we may want to revisit this later. In particular, for filters that check EQUAL to default value.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util_test.cc, line 188 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbPimOr3ctRIUSadED_:-MbPimOr3ctRIUSadEDa:bfimc0j) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/07cb280c5e876d9f04a8d9988f7fda9b42b00824/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util_test.cc#L188)):*
> ```
>       EqualsProto(test_proto.a().b()));
> ```
Maybe use an explicit default TestProtoB to be clear.
___
*[src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util_test.cc, line 311 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/12#-MbPjQ7ZDgB4sBaVQaHO:-MbPjQ7_1mFD858LzluA:bfimc0j) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/07cb280c5e876d9f04a8d9988f7fda9b42b00824/src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util_test.cc#L311)):*
> ```
>       EqualsProto(test_proto.a().b()));
> ```
Maybe use an explicit default TestProtoB to be clear.

**Pull request merged**
