### PR TITLE
Add protobuf for geometric shredding.

### PR DESCRIPTION
**Pull request by tcsnfkx**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/60)

**Review by wliue — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/60)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @EvgSkv, @stevenwarejones, and @tcsnfkx)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/60#-NYQ1pER6QOHWJ57naHW):*
thredding -> shredding
___
*[`src/main/proto/wfa/virtual_people/common/model.proto` line 254 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/60#-NYQ0ZFFEvusUgG6DIgy:-NYQ0ZFFEvusUgG6DIgz:bfwa7ay) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/376d8da42216076176c31c8aacbbe58ba927c6eb/src/main/proto/wfa/virtual_people/common/model.proto#L254)):*
> ```proto
> 
>   // The field to apply the hash to.
>   optional string field_to_hash = 2;
> ```

Normally acting_fingerprint is used as source of randomness, but for the use case that updating acting_fingerprint it doesn't work. I think the purpose of this field is for the MP to specify source of randomness, not for applying hash. The hash should apply to target_field.



_Code quote:_
```proto
  // The field to apply the hash to.
  optional string field_to_hash = 2;
```

**Review by tcsnfkx — COMMENTED** [review]
> Dismissed @wliue from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/60)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @EvgSkv and @stevenwarejones)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/60#-NYQ1pER6QOHWJ57naHW):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

thredding -> shredding
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/virtual_people/common/model.proto` line 254 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/60#-NYQ0ZFFEvusUgG6DIgy:-NYZHHcZBtA2fkdqr959:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/376d8da42216076176c31c8aacbbe58ba927c6eb/src/main/proto/wfa/virtual_people/common/model.proto#L254)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

Normally acting_fingerprint is used as source of randomness, but for the use case that updating acting_fingerprint it doesn't work. I think the purpose of this field is for the MP to specify source of randomness, not for applying hash. The hash should apply to target_field.
</blockquote></details>

Done.

**Review by wliue — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/60)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @EvgSkv, @stevenwarejones, and @tcsnfkx)

___
*[`src/main/proto/wfa/virtual_people/common/model.proto` line 255 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/60#-NYZOI7FA85jmJMJjihk:-NYZOI7FA85jmJMJjihl:b-62kkld) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e194232a18928a1d7e350feb1b74bc398197f7ea/src/main/proto/wfa/virtual_people/common/model.proto#L255)):*
> ```proto
>   optional string randomness_field = 2;
> 
>   // The field to apply the hash to.
> ```

The hashing is implementation details. Could just say "to apply the shredding to".



_Code quote:_
```proto
// The field to apply the hash to.
```

**Review by tcsnfkx — COMMENTED** [review]
> Dismissed @wliue from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/60)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @EvgSkv and @stevenwarejones)

___
*[`src/main/proto/wfa/virtual_people/common/model.proto` line 255 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/60#-NYZOI7FA85jmJMJjihk:-NYZpnb02PmoED8w7VKl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/e194232a18928a1d7e350feb1b74bc398197f7ea/src/main/proto/wfa/virtual_people/common/model.proto#L255)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

The hashing is implementation details. Could just say "to apply the shredding to".
</blockquote></details>

Done.

**Review by EvgSkv — APPROVED** [review]

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/60)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @wangyaopw)

**Pull request merged**
