### PR TITLE
Golden Generator for Integration Testing Framework

### PR DESCRIPTION
**Pull request by wastadtlander**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34)

### CODE REVIEW

**Review by tcsnfkx — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34)* status: all files reviewed, 14 unresolved discussions (waiting on @EvgSkv, @wastadtlander, and @wliue)

___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.h` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D7uPd9ftAom8pa8cZ:-N9D7uPd9ftAom8pa8c_:b-wz7vd0) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.h#L27)):*
> ```objc
> // Generates CLI commands to generate golden files of binaries based on input
> // config.
> std::vector<std::string> GoldenGenerator(const IntegrationTestList config);
> ```

I think it should be "const IntegrationTestList&"



_Code quote:_
```objc
const IntegrationTestList
```
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D8Nxx4cdONTazQRU1:-N9D8Nxx4cdONTazQRU2:b-b8gxv4) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L32)):*
> ```cpp
> std::vector<std::string> GoldenGenerator(const IntegrationTestList config) {
>   std::unique_ptr<Runfiles> runfiles(Runfiles::CreateForTest());
>   std::vector<std::string> executeVector;
> ```

Could you please change this to execute_vector?



_Code quote:_
```cpp
executeVector
```
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D95_2ALAbDtWhh45M:-N9D95_2ALAbDtWhh45N:b2nreh6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L35)):*
> ```cpp
>   std::string execute;
> 
>   for (int testIndex = 0; testIndex < config.tests_size(); testIndex++) {
> ```

Same as above.



_Code quote:_
```cpp
testIndex
```
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D9RTD-m_9RV3A74H_:-N9D9RTD-m_9RV3A74Ha:bpv965n) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L36)):*
> ```cpp
> 
>   for (int testIndex = 0; testIndex < config.tests_size(); testIndex++) {
>     IntegrationTest it = config.tests().at(testIndex);
> ```

I think this should be "const IntegrationTest&"



_Code quote:_
```cpp
IntegrationTest
```
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D9YLADy4UOJti8s4S:-N9D9YLADy4UOJti8s4T:b2nreh6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L38)):*
> ```cpp
>     IntegrationTest it = config.tests().at(testIndex);
>     std::string binaryPath = runfiles->Rlocation(it.binary());
>     for (int testCaseIndex = 0; testCaseIndex < it.test_cases_size();
> ```

Same as above.



_Code quote:_
```cpp
testCaseIndex
```
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D9b6t87YCRrz_7uIx:-N9D9b6t87YCRrz_7uIy:b-hjkpfn) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L40)):*
> ```cpp
>     for (int testCaseIndex = 0; testCaseIndex < it.test_cases_size();
>          testCaseIndex++) {
>       TestCase tc = it.test_cases().at(testCaseIndex);
> ```

const TestCase&?



_Code quote:_
```cpp
TestCase
```
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D9f142GvHj-UqehDG:-N9D9f142GvHj-UqehDH:b2nreh6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L42)):*
> ```cpp
>       TestCase tc = it.test_cases().at(testCaseIndex);
>       execute = binaryPath;
>       for (int binaryParameterIndex = 0;
> ```

Same as above.



_Code quote:_
```cpp
binaryParameterIndex
```
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D9mHx2PIoolpYpQfQ:-N9D9mHx2PIoolpYpQfR:bggbdi8) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L46)):*
> ```cpp
>            binaryParameterIndex++) {
>         BinaryParameter bp = tc.binary_parameters().at(binaryParameterIndex);
>         execute += " --" + bp.name() + "=";
> ```

Maybe use absl::StrCat or absl::StrAppend?
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D9tPy8fn_qJfDCBBJ:-N9D9tPy8fn_qJfDCBBK:b-ya81ng) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L48)):*
> ```cpp
>         execute += " --" + bp.name() + "=";
>         if (bp.golden().empty()) {
>           execute += bp.value();
> ```

Same as above
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D9uMI5keB2UJLd1Z4:-N9D9uMI5keB2UJLd1Z5:b-ya81ng) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L50)):*
> ```cpp
>           execute += bp.value();
>         } else {
>           execute += bp.golden();
> ```

Same as above
___
*[`src/main/proto/wfa/virtual_people/common/config.proto` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9DA-rH5E_dghOV71DC:-N9DA-rH5E_dghOV71DD:b-ie49kc) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/proto/wfa/virtual_people/common/config.proto#L19)):*
> ```protobuf
> package wfa_virtual_people;
> 
> message BinaryParameter {
> ```

Could you please add some comments about the fields and the messages, and maybe also add some examples?
___
*[`src/test/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator_test.cc` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9DAFls46VppyW1jJXM:-N9DAFls46VppyW1jJXN:b-b8gxv4) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/test/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator_test.cc#L30)):*
> ```cpp
> TEST(GoldenGeneratorTest, EmptyConfig) {
>   IntegrationTestList config;
>   std::vector<std::string> executeVector(GoldenGenerator(config));
> ```

Could you please change this to execute_vector?



_Code quote:_
```cpp
executeVector
```
___
*[`src/test/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator_test.cc` line 105 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9DANKcAFUcr0fVgAXc:-N9DANKcAFUcr0fVgAXd:b2nreh6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/test/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator_test.cc#L105)):*
> ```cpp
>       )pb",
>       &config));
>   std::vector<std::string> executeVector(GoldenGenerator(config));
> ```

Same as above.



_Code quote:_
```cpp
executeVector
```
___
*[`src/test/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator_test.cc` line 108 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9DATZd0pQup9auokip:-N9DATZd0pQup9auokiq:b-e7gekb) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/test/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator_test.cc#L108)):*
> ```cpp
> 
>   for (int i = 0; i < executeVector.size(); i++) {
>     int index = executeVector[i].find("bazel-out");
> ```

How about making this a global const?



_Code quote:_
```cpp
"bazel-out"
```

**Review by wastadtlander — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34)* status: all files reviewed, 14 unresolved discussions (waiting on @EvgSkv, @tcsnfkx, and @wliue)

___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.h` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D7uPd9ftAom8pa8cZ:-N9DZrjKDpK-oSsCX4AJ:bs7wumb) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.h#L27)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

I think it should be "const IntegrationTestList&"
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D8Nxx4cdONTazQRU1:-N9D_jOV729KUH6Hc5_K:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L32)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Could you please change this to execute_vector?
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D95_2ALAbDtWhh45M:-N9D_snD7qUgEIKslw-T:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L35)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D9RTD-m_9RV3A74H_:-N9D_yv8Du9l51auI_Q2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L36)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

I think this should be "const IntegrationTest&"
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D9YLADy4UOJti8s4S:-N9Da1ZB4cwoFiw66EHC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L38)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D9b6t87YCRrz_7uIx:-N9Da5zOBMMyQKhllFic:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L40)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

const TestCase&?
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D9f142GvHj-UqehDG:-N9DaKAM8zPx7e9yzVPl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L42)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D9mHx2PIoolpYpQfQ:-N9DbnQKA9os05GCVcZC:b-1iatym) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L46)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Maybe use absl::StrCat or absl::StrAppend?
</blockquote></details>

Switched to absl::StrCat.
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D9tPy8fn_qJfDCBBJ:-N9DcFnR2KWjDlGJKEb9:b-tmsdrg) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L48)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Switched to absl::StrAppend
___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9D9uMI5keB2UJLd1Z4:-N9DcHu_8uKd5YbNYtBv:b62inlc) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L50)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Switched to absl::StrAppend.
___
*[`src/main/proto/wfa/virtual_people/common/config.proto` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9DA-rH5E_dghOV71DC:-N9Dg40i2seK52k3j6Mw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/main/proto/wfa/virtual_people/common/config.proto#L19)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Could you please add some comments about the fields and the messages, and maybe also add some examples?
</blockquote></details>

Done.
___
*[`src/test/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator_test.cc` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9DAFls46VppyW1jJXM:-N9DgCNZDc5hacPkZb47:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/test/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator_test.cc#L30)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Could you please change this to execute_vector?
</blockquote></details>

Done.
___
*[`src/test/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator_test.cc` line 105 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9DANKcAFUcr0fVgAXc:-N9DgDgREUIg3Il3T_Xd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/test/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator_test.cc#L105)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`src/test/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator_test.cc` line 108 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9DATZd0pQup9auokip:-N9DhTsT4iiWr2qG3qSh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/40c3d7e6ccc72b6540ba5752892ce7a0f4524a5d/src/test/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator_test.cc#L108)):*
<details><summary><i>Previously, tcsnfkx wrote…</i></summary><blockquote>

How about making this a global const?
</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34)* status: 4 of 7 files reviewed, 16 unresolved discussions (waiting on @EvgSkv, @stevenwarejones, @tcsnfkx, @wastadtlander, and @wliue)

___
*[`src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc` line 36 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9Ybt7Z8gfPnhd15NI-:-N9Ybt7Z8gfPnhd15NI0:b-ferscn) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/aa631602aa84d053545961718a3634ffb59c146a/src/main/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator.cc#L36)):*
> ```cpp
>   std::string execute;
> 
>   for (int test_index = 0; test_index < config.tests_size(); test_index++) {
> ```

Nit: always do `++i`



_Code quote:_
```cpp
test_index++
```
___
*[`src/test/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator_test.cc` line 124 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9YdL8g279eaK0IWUYc:-N9YdL8g279eaK0IWUYd:b65nm0n) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/aa631602aa84d053545961718a3634ffb59c146a/src/test/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator_test.cc#L124)):*
> ```cpp
>   EXPECT_THAT(
>       execute_vector,
>       ::testing::ElementsAre(
> ```

Consider defining several temp variables for these elements before this.
```
std::string element_1=xx
std::string element_2=xx
std::string element_3=xx
  EXPECT_THAT(
      execute_vector,
      ::testing::ElementsAre(element_1,...,element_n)
)
...
```




_Code quote:_
```cpp
::testing::ElementsAre(
```

**Review by wastadtlander — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34)* status: 4 of 7 files reviewed, 15 unresolved discussions (waiting on @EvgSkv, @stevenwarejones, @tcsnfkx, @wangyaopw, and @wliue)

___
*[`src/test/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator_test.cc` line 124 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34#-N9YdL8g279eaK0IWUYc:-N9YhcEdC5erOkK5q94J:bs7wumb) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/aa631602aa84d053545961718a3634ffb59c146a/src/test/cc/wfa/virtual_people/common/integration_testing_framework/golden_generator_test.cc#L124)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Consider defining several temp variables for these elements before this.
```
std::string element_1=xx
std::string element_2=xx
std::string element_3=xx
  EXPECT_THAT(
      execute_vector,
      ::testing::ElementsAre(element_1,...,element_n)
)
...
```

</blockquote></details>

Done.

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 1 of 1 files at r2, 2 of 5 files at r3, 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34)* status: all files reviewed, 14 unresolved discussions (waiting on @EvgSkv, @stevenwarejones, @tcsnfkx, and @wliue)

**Review by tcsnfkx — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EvgSkv, @stevenwarejones, and @wliue)

**Pull request merged**
